In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

TRACKS_PATH = (
    PROJECT_ROOT / "data" / "raw" / "tracks" / "tracks.csv"
)
FLEET_PATH = (
    PROJECT_ROOT / "data" / "raw" / "fleets" / "fleet.csv"
)
SPEED_FEATURES_PATH = (
    PROJECT_ROOT / "data" / "interim" / "speed_features.csv"
)

tracks = pd.read_csv(TRACKS_PATH)
fleet = pd.read_csv(FLEET_PATH)
speed_features = pd.read_csv(SPEED_FEATURES_PATH)

print("Tracks:", tracks.shape)
print("Fleet:", fleet.shape)
print("Speed features:", speed_features.shape)

Tracks: (151598, 19)
Fleet: (163, 5)
Speed features: (151598, 13)

In [3]:
df = tracks.merge(
    fleet,
    on="vehicle_id",
    how="left",
    validate="many_to_one",
    suffixes=("", "_fleet")
)

df = df.merge(
    speed_features,
    on=["vehicle_id", "track_id"],
    how="left",
    validate="one_to_one",
    suffixes=("", "_speed")
)

print("Merged dataset:", df.shape)
print("Missing vehicle specifications:",
      df["gross_vehicle_weight"].isna().sum())
print("Missing raw speed means:",
      df["raw_speed_mean"].isna().sum())

Merged dataset: (151598, 34)
Missing vehicle specifications: 25021
Missing raw speed means: 9

In [4]:
# 1. Check missing vehicle specifications
missing_specs = df[df["gross_vehicle_weight"].isna()]

print("Tracks with missing vehicle specifications:",
      len(missing_specs))
print("Unique affected vehicles:",
      missing_specs["vehicle_id"].nunique())
print("\nAffected vehicle IDs:")
print(sorted(missing_specs["vehicle_id"].unique()))

# 2. Inspect tracks with missing raw speed means
missing_speed = df[df["raw_speed_mean"].isna()]

speed_columns = [
    "vehicle_id",
    "track_id",
    "raw_observations",
    "telemetry_span_seconds",
    "raw_speed_mean",
    "raw_speed_min",
    "raw_speed_max",
    "missing_speed_count",
]

print("\nTracks with missing raw speed means:",
      len(missing_speed))
print(missing_speed[speed_columns].to_string(index=False))

# 3. Check whether the other raw speed statistics are missing too
print("\nMissing-value counts across speed features:")
print(
    df[
        [
            "raw_observations",
            "raw_speed_mean",
            "raw_speed_std",
            "raw_speed_min",
            "raw_speed_max",
        ]
    ].isna().sum()
)

Tracks with missing vehicle specifications: 25021
Unique affected vehicles: 14

Affected vehicle IDs:
[np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(125)]

Tracks with missing raw speed means: 9
 vehicle_id  track_id  raw_observations  telemetry_span_seconds  raw_speed_mean  raw_speed_min  raw_speed_max  missing_speed_count
         90    132379                 0                     NaN             NaN            NaN            NaN                    0
         90    132420                 0                     NaN             NaN            NaN            NaN                    0
        109    136589                 0                     NaN             NaN            NaN            NaN                    0
        109    136918                 0                     NaN             NaN            NaN            NaN                    0
        116    138378                 0                     NaN             NaN            NaN            NaN                    0
        146    146183                 0                     NaN             NaN            NaN            NaN                    0
        155    148765                 0                     NaN             NaN            NaN            NaN                    0
        156    149007                 0                     NaN             NaN            NaN            NaN                    0
        159    150015                 0                     NaN             NaN            NaN            NaN                    0

Missing-value counts across speed features:
raw_observations     0
raw_speed_mean       9
raw_speed_std       14
raw_speed_min        9
raw_speed_max        9
dtype: int64

In [7]:
# Work on a separate copy; preserve df and all original values.
features = df.copy()

# --------------------------------------------------
# A. TELEMETRY SUFFICIENCY
# --------------------------------------------------
features["insufficient_telemetry"] = (
    features["raw_observations"] < 3
)

# --------------------------------------------------
# B. DURATION VALIDITY
# --------------------------------------------------
features["start_time_parsed"] = pd.to_datetime(
    features["start_time"],
    format="mixed",
    utc=True,
    errors="coerce"
)

features["stop_time_parsed"] = pd.to_datetime(
    features["stop_time"],
    format="mixed",
    utc=True,
    errors="coerce"
)

features["duration_seconds"] = (
    features["stop_time_parsed"]
    - features["start_time_parsed"]
).dt.total_seconds()

features["duration_invalid"] = (
    features["duration_seconds"] < 0
)

# --------------------------------------------------
# C. SPEED SUMMARY FLAGS
# --------------------------------------------------
features["avg_speed_negative"] = (
    features["avg_speed"] < 0
)

features["avg_speed_gt_max_speed"] = (
    features["avg_speed"] > features["max_speed"]
)

features["raw_speed_missing"] = (
    features["raw_speed_mean"].isna()
)

# --------------------------------------------------
# D. SIGNAL-LOSS FLAGS
# --------------------------------------------------
features["n_signal_loss_negative"] = (
    features["n_signal_loss"] < 0
)

features["r_signal_loss_missing"] = (
    features["r_signal_loss"].isna()
)

features["r_signal_loss_out_of_range"] = (
    (features["r_signal_loss"] < 0)
    | (features["r_signal_loss"] > 1)
)

# --------------------------------------------------
# E. DISTANCE AND TRACK-GAP FLAGS
# --------------------------------------------------
features["distance_missing"] = (
    features["distance"].isna()
)

features["zero_distance"] = (
    features["distance"] == 0
)

features["zero_distance_speed_issue"] = (
    (features["distance"] == 0)
    & (features["max_speed"] > 1)
)

features["track_gap_missing"] = (
    features["track_gap"].isna()
)

# --------------------------------------------------
# F. REPORT FLAG COUNTS
# --------------------------------------------------
flag_columns = [
    "insufficient_telemetry",
    "duration_invalid",
    "avg_speed_negative",
    "avg_speed_gt_max_speed",
    "raw_speed_missing",
    "n_signal_loss_negative",
    "r_signal_loss_missing",
    "r_signal_loss_out_of_range",
    "distance_missing",
    "zero_distance",
    "zero_distance_speed_issue",
    "track_gap_missing",
]

print("Candidate quality-flag counts:")
print(features[flag_columns].sum().sort_values(ascending=False))

Candidate quality-flag counts:
avg_speed_gt_max_speed        45819
n_signal_loss_negative         1927
r_signal_loss_missing          1714
zero_distance                  1665
zero_distance_speed_issue       188
track_gap_missing               163
r_signal_loss_out_of_range       90
insufficient_telemetry           70
distance_missing                 49
duration_invalid                  9
raw_speed_missing                 9
avg_speed_negative                6
dtype: int64

In [8]:
# Inspect tracks marked as having insufficient telemetry
insufficient = features.loc[
    features["insufficient_telemetry"],
    [
        "vehicle_id",
        "track_id",
        "raw_observations",
        "raw_speed_mean",
        "distance",
        "avg_speed",
        "max_speed",
    ],
]

print("Flagged tracks:", len(insufficient))
print("\nObservation-count distribution:")
print(insufficient["raw_observations"].value_counts(dropna=False).sort_index())

print("\nTracks with missing raw speed mean:",
      insufficient["raw_speed_mean"].isna().sum())

print("\nTracks with missing distance:",
      insufficient["distance"].isna().sum())

display(insufficient.head(15))

Flagged tracks: 70

Observation-count distribution:
raw_observations
0     9
1     5
2    56
Name: count, dtype: int64

Tracks with missing raw speed mean: 9

Tracks with missing distance: 49

,vehicle_id,track_id,raw_observations,raw_speed_mean,distance,avg_speed,max_speed
85088,44,85088,2,0.025,NaN,NaN,NaN
85199,44,85199,2,0.015,NaN,NaN,NaN
85239,44,85239,2,0.015,NaN,NaN,NaN
85455,44,85455,2,0.025,NaN,NaN,NaN
85521,44,85521,2,0.020,NaN,NaN,NaN
85533,44,85533,2,0.020,0.0,0.0,0.03
85574,44,85574,2,0.035,NaN,NaN,NaN
85668,44,85668,2,0.040,0.0,0.0,0.06
85817,44,85817,2,0.040,NaN,NaN,NaN
86303,44,86303,2,0.060,NaN,NaN,NaN
86400,44,86400,2,0.050,NaN,NaN,NaN
86462,44,86462,2,0.045,NaN,NaN,NaN
86583,44,86583,2,0.025,NaN,NaN,NaN
86791,44,86791,2,0.020,0.0,0.0,0.02
87001,44,87001,2,0.035,NaN,NaN,NaN

In [9]:
# Fewer than 3 recorded telemetry observations
features["limited_telemetry"] = (
    features["raw_observations"] < 3
)

# Missing essential track measurements
features["insufficient_core_telemetry"] = (
    features["distance"].isna()
    | features["avg_speed"].isna()
    | features["max_speed"].isna()
)

In [30]:
# Work on the existing features dataframe.
# Preserve the original columns unchanged.

features["avg_speed_valid"] = features["avg_speed"].where(
    features["avg_speed"] >= 0
)

features["max_speed_valid"] = features["max_speed"].where(
    features["max_speed"] >= 0
)

features["n_signal_loss_valid"] = features["n_signal_loss"].where(
    features["n_signal_loss"] >= 0
)

features["r_signal_loss_valid"] = features["r_signal_loss"].where(
    features["r_signal_loss"].between(0, 1)
)

# Unit conversions
features["distance_km"] = features["distance"] / 1000

features["avg_speed_kmh"] = (
    features["avg_speed_valid"] * 3.6
)

features["max_speed_kmh"] = (
    features["max_speed_valid"] * 3.6
)

features["raw_speed_mean_kmh"] = (
    features["raw_speed_mean"] * 3.6
)

# Duration derived from timestamps
features["duration_minutes"] = (
    features["duration_seconds"] / 60
).where(features["duration_seconds"] >= 0)

# Verify the new columns
new_columns = [
    "avg_speed_valid",
    "max_speed_valid",
    "n_signal_loss_valid",
    "r_signal_loss_valid",
    "distance_km",
    "avg_speed_kmh",
    "max_speed_kmh",
    "raw_speed_mean_kmh",
    "duration_minutes",
]

display(features[new_columns].describe().T)

,count,mean,std,min,25%,50%,75%,max
avg_speed_valid,151543.0,3.621383,10.185694,0.000000,0.160000,0.590000,3.420000,1230.790000
max_speed_valid,151549.0,7.474009,9.809897,0.020000,0.130000,1.450000,15.210000,126.650000
n_signal_loss_valid,149622.0,1370.528672,9972.579609,0.000000,0.000000,1.000000,5.000000,532659.000000
r_signal_loss_valid,149794.0,0.009465,0.051525,0.000000,0.000000,0.000000,0.000035,0.999830
distance_km,151549.0,14.526373,42.081918,0.000000,0.020000,0.116000,2.058000,476.551000
avg_speed_kmh,151543.0,13.036978,36.668497,0.000000,0.576000,2.124000,12.312000,4430.844000
max_speed_kmh,151549.0,26.906431,35.315628,0.072000,0.468000,5.220000,54.756000,455.940000
raw_speed_mean_kmh,151589.0,12.339849,21.368028,0.033398,0.093719,0.529386,13.177681,340.224923
duration_minutes,151589.0,22.392300,42.244470,0.003350,1.090467,5.916250,20.620750,1029.733783

In [11]:
# Inspect the 20 highest track-level average speeds
speed_cols = [
    "vehicle_id",
    "track_id",
    "distance_km",
    "duration_minutes",
    "avg_speed",
    "max_speed",
    "raw_observations",
    "raw_speed_mean",
    "raw_speed_max",
    "avg_speed_gt_max_speed",
    "limited_telemetry",
]

display(
    features.nlargest(20, "avg_speed")[speed_cols]
)

# Compare track-level and raw telemetry speed summaries
print("Correlation between speed summaries:")
display(
    features[
        ["avg_speed", "max_speed", "raw_speed_mean", "raw_speed_max"]
    ].corr(method="spearman")
)

# Inspect the highest raw telemetry mean speeds
display(
    features.nlargest(20, "raw_speed_mean")[speed_cols]
)

,vehicle_id,track_id,distance_km,duration_minutes,avg_speed,max_speed,raw_observations,raw_speed_mean,raw_speed_max,avg_speed_gt_max_speed,limited_telemetry
138274,114,138274,277.421,3.756667,1230.79,2.33,2186,0.536395,2.33,True,False
49132,22,49132,182.083,2.706517,1121.26,9.15,1594,1.959812,9.15,True,False
135017,102,135017,68.080,1.085617,1045.18,6.86,646,1.956362,6.86,True,False
102170,54,102170,17.535,0.280250,1042.82,0.07,166,0.023193,0.07,True,False
93407,48,93407,104.576,2.277983,765.12,0.09,1342,0.022481,0.09,True,False
9707,5,9707,12.865,0.280383,764.73,0.07,166,0.025843,0.07,True,False
138899,118,138899,117.550,2.644717,740.79,6.78,1457,0.993473,6.78,True,False
91783,47,91783,226.810,5.702400,662.91,9.90,3358,3.061873,9.90,True,False
143352,135,143352,106.570,2.738200,648.66,13.56,1618,5.803560,13.56,True,False
150232,159,150232,88.133,2.312567,635.17,4.55,1375,1.051796,4.55,True,False
104890,54,104890,39.176,1.279283,510.39,4.93,754,1.581021,4.93,True,False
114748,59,114748,149.795,5.131883,486.49,0.95,3022,0.022862,0.95,True,False
103102,54,103102,99.819,3.562450,467.00,2.26,2098,0.113999,2.26,True,False
29944,15,29944,269.965,10.478233,429.41,18.72,6130,9.905388,18.72,True,False
105234,54,105234,114.082,4.703800,404.22,5.37,2770,1.349917,5.37,True,False
61101,27,61101,92.787,3.847283,401.96,1.15,2266,0.267458,1.15,True,False
132992,92,132992,69.171,3.706750,311.01,2.88,2186,0.163701,2.88,True,False
131935,88,131935,75.433,4.221217,297.83,11.55,2509,3.076321,11.55,True,False
146128,146,146128,62.017,3.812167,271.14,0.24,2266,0.047983,0.24,True,False
11767,6,11767,170.415,10.603417,267.86,0.13,6214,0.024171,0.13,True,False

Correlation between speed summaries:

                avg_speed  max_speed  raw_speed_mean  raw_speed_max
avg_speed        1.000000   0.810304        0.856755       0.810222
max_speed        0.810304   1.000000        0.944445       0.999907
raw_speed_mean   0.856755   0.944445        1.000000       0.944202
raw_speed_max    0.810222   0.999907        0.944202       1.000000

,vehicle_id,track_id,distance_km,duration_minutes,avg_speed,max_speed,raw_observations,raw_speed_mean,raw_speed_max,avg_speed_gt_max_speed,limited_telemetry
42896,20,42896,0.000,1.123383,0.00,97.68,78,94.506923,94.95,False,False
49358,22,49358,0.000,11.396667,0.00,98.17,2737,94.336598,98.17,False,False
2775,2,2775,5.865,2.519133,38.80,84.82,76,70.896316,84.82,False,False
106166,54,106166,0.000,4.038717,0.00,70.51,29,70.010000,70.51,False,False
81401,40,81401,0.150,36.663800,0.07,72.77,41,69.216585,72.77,False,False
147501,150,147501,0.000,4.150733,0.00,70.27,37,67.959189,70.27,False,False
27588,14,27588,10.922,39.650367,4.59,70.95,667,67.148936,70.95,False,False
25431,13,25431,0.000,3.546767,0.00,71.57,24,65.588750,71.57,False,False
3851,2,3851,0.331,0.093483,59.01,69.25,48,62.398542,69.25,False,False
81376,40,81376,0.205,0.133817,25.53,75.69,6,58.183333,75.69,False,False
50697,23,50697,0.000,9.499950,0.00,68.50,410,57.795610,68.50,False,False
3154,2,3154,2.078,14.506683,2.39,63.19,11,53.532727,63.19,False,False
3877,2,3877,1.259,3.468783,6.05,75.88,78,50.016026,75.88,False,False
81386,40,81386,0.854,1.195967,11.90,63.74,76,49.658684,63.74,False,False
108676,55,108676,2.648,8.075917,5.46,49.82,34,48.989118,49.82,False,False
91554,47,91554,0.198,3.021350,1.09,46.43,19,46.377368,46.43,False,False
2626,2,2626,0.141,0.992083,2.37,44.79,32,44.358438,44.79,False,False
3833,2,3833,0.054,2.284783,0.39,43.06,15,42.606000,43.06,False,False
6344,4,6344,0.056,3.046617,0.31,40.27,14,40.160714,40.27,False,False
81388,40,81388,7.726,4.047650,31.81,44.76,124,40.114677,44.76,False,False

In [12]:
# Examine the distribution of positive average speeds
positive_avg_speed = features.loc[
    features["avg_speed"] > 0,
    "avg_speed"
]

display(
    positive_avg_speed.describe(
        percentiles=[
            0.50, 0.75, 0.90, 0.95, 0.99, 0.995
        ]
    ).to_frame("avg_speed_mps")
)

# Inspect the 30 records with the highest average speeds
high_speed_records = features.nlargest(
    30, "avg_speed"
).copy()

high_speed_records["avg_speed_kmh_check"] = (
    high_speed_records["avg_speed"] * 3.6
)

high_speed_records["max_speed_kmh_check"] = (
    high_speed_records["max_speed"] * 3.6
)

display(
    high_speed_records[
        [
            "vehicle_id",
            "track_id",
            "distance",
            "duration_seconds",
            "avg_speed",
            "max_speed",
            "raw_observations",
            "raw_speed_mean",
            "raw_speed_max",
            "avg_speed_gt_max_speed",
            "limited_telemetry",
        ]
    ]
)

       avg_speed_mps
count  149420.000000
mean        3.672836
std        10.248584
min         0.010000
50%         0.620000
75%         3.550000
90%        13.740000
95%        17.640000
99%        21.390000
99.5%      22.329050
max      1230.790000

,vehicle_id,track_id,distance,duration_seconds,avg_speed,max_speed,raw_observations,raw_speed_mean,raw_speed_max,avg_speed_gt_max_speed,limited_telemetry
138274,114,138274,277421.0,225.400,1230.79,2.33,2186,0.536395,2.33,True,False
49132,22,49132,182083.0,162.391,1121.26,9.15,1594,1.959812,9.15,True,False
135017,102,135017,68080.0,65.137,1045.18,6.86,646,1.956362,6.86,True,False
102170,54,102170,17535.0,16.815,1042.82,0.07,166,0.023193,0.07,True,False
93407,48,93407,104576.0,136.679,765.12,0.09,1342,0.022481,0.09,True,False
9707,5,9707,12865.0,16.823,764.73,0.07,166,0.025843,0.07,True,False
138899,118,138899,117550.0,158.683,740.79,6.78,1457,0.993473,6.78,True,False
91783,47,91783,226810.0,342.144,662.91,9.90,3358,3.061873,9.90,True,False
143352,135,143352,106570.0,164.292,648.66,13.56,1618,5.803560,13.56,True,False
150232,159,150232,88133.0,138.754,635.17,4.55,1375,1.051796,4.55,True,False
104890,54,104890,39176.0,76.757,510.39,4.93,754,1.581021,4.93,True,False
114748,59,114748,149795.0,307.913,486.49,0.95,3022,0.022862,0.95,True,False
103102,54,103102,99819.0,213.747,467.00,2.26,2098,0.113999,2.26,True,False
29944,15,29944,269965.0,628.694,429.41,18.72,6130,9.905388,18.72,True,False
105234,54,105234,114082.0,282.228,404.22,5.37,2770,1.349917,5.37,True,False
61101,27,61101,92787.0,230.837,401.96,1.15,2266,0.267458,1.15,True,False
132992,92,132992,69171.0,222.405,311.01,2.88,2186,0.163701,2.88,True,False
131935,88,131935,75433.0,253.273,297.83,11.55,2509,3.076321,11.55,True,False
146128,146,146128,62017.0,228.730,271.14,0.24,2266,0.047983,0.24,True,False
11767,6,11767,170415.0,636.205,267.86,0.13,6214,0.024171,0.13,True,False
147030,149,147030,127250.0,515.030,247.07,21.59,5101,8.019688,21.59,True,False
150461,160,150461,134152.0,548.053,244.78,11.39,5426,1.393328,11.39,True,False
136282,108,136282,41949.0,171.474,244.64,8.16,1699,2.939005,8.16,True,False
128259,73,128259,71769.0,302.344,237.38,4.76,2995,0.992431,4.76,True,False
147222,149,147222,73293.0,311.895,234.99,5.93,3077,0.925645,5.93,True,False
122402,63,122402,28922.0,128.656,224.80,2.49,1205,0.526539,2.49,True,False
74467,35,74467,137462.0,703.058,195.52,0.20,6631,0.025449,0.20,True,False
5581,3,5581,54903.0,282.231,194.53,5.37,2770,0.315679,5.37,True,False
104223,54,104223,129122.0,697.978,184.99,14.60,6803,5.966884,14.60,True,False
115472,59,115472,90390.0,497.633,181.64,8.99,4870,0.711162,8.99,True,False

In [13]:
# Conservative threshold for investigating implausible truck speeds
AVG_SPEED_THRESHOLD_KMH = 120
AVG_SPEED_THRESHOLD_MPS = AVG_SPEED_THRESHOLD_KMH / 3.6

# Flag physically implausible reported average speeds
features["avg_speed_implausible"] = (
    features["avg_speed"] > AVG_SPEED_THRESHOLD_MPS
)

# Keep this separate from the speed-summary inconsistency flag
features["avg_speed_gt_max_speed"] = (
    features["avg_speed"] > features["max_speed"]
)

print(
    f"Average-speed threshold: "
    f"{AVG_SPEED_THRESHOLD_KMH} km/h "
    f"({AVG_SPEED_THRESHOLD_MPS:.2f} m/s)"
)

print(
    "Records above threshold:",
    features["avg_speed_implausible"].sum()
)

print(
    "Percentage of all records:",
    round(features["avg_speed_implausible"].mean() * 100, 3),
    "%"
)

print(
    "Records where average speed exceeds maximum speed:",
    features["avg_speed_gt_max_speed"].sum()
)

print(
    "Records satisfying both conditions:",
    (
        features["avg_speed_implausible"]
        & features["avg_speed_gt_max_speed"]
    ).sum()
)

Average-speed threshold: 120 km/h (33.33 m/s)
Records above threshold: 236
Percentage of all records: 0.156 %
Records where average speed exceeds maximum speed: 45819
Records satisfying both conditions: 234

In [14]:
# Inspect all records above the chosen average-speed threshold
high_speed_records = features.loc[
    features["avg_speed_implausible"]
].copy()

# Calculate distance / elapsed-time speed independently
high_speed_records["implied_speed_kmh"] = (
    high_speed_records["distance"]
    / high_speed_records["duration_seconds"]
    * 3.6
).where(
    high_speed_records["duration_seconds"] > 0
)

# Compare reported and independently implied speed
high_speed_records["speed_difference_kmh"] = (
    high_speed_records["avg_speed"] * 3.6
    - high_speed_records["implied_speed_kmh"]
)

display(
    high_speed_records[
        [
            "vehicle_id",
            "track_id",
            "distance",
            "duration_seconds",
            "avg_speed",
            "max_speed",
            "raw_observations",
            "raw_speed_mean",
            "raw_speed_max",
            "implied_speed_kmh",
            "avg_speed_gt_max_speed",
        ]
    ].sort_values("avg_speed", ascending=False)
)

,vehicle_id,track_id,distance,duration_seconds,avg_speed,max_speed,raw_observations,raw_speed_mean,raw_speed_max,implied_speed_kmh,avg_speed_gt_max_speed
138274,114,138274,277421.0,225.400,1230.79,2.33,2186,0.536395,2.33,4430.858917,True
49132,22,49132,182083.0,162.391,1121.26,9.15,1594,1.959812,9.15,4036.546360,True
135017,102,135017,68080.0,65.137,1045.18,6.86,646,1.956362,6.86,3762.654098,True
102170,54,102170,17535.0,16.815,1042.82,0.07,166,0.023193,0.07,3754.148082,True
93407,48,93407,104576.0,136.679,765.12,0.09,1342,0.022481,0.09,2754.436307,True
...,...,...,...,...,...,...,...,...,...,...,...
129424,76,129424,58402.0,1735.688,33.65,10.68,16148,1.679937,10.68,121.131908,True
120929,62,120929,29409.0,874.700,33.62,8.55,8566,0.618335,8.55,121.038527,True
109536,56,109536,17535.0,523.347,33.51,0.35,5123,0.029262,0.35,120.619780,True
137764,112,137764,86463.0,2581.185,33.50,25.75,25189,16.426957,25.75,120.590659,True
117452,59,117452,48527.0,1454.124,33.37,24.01,13435,8.911087,24.01,120.139135,True

In [15]:
# Identify records above the 120 km/h average-speed threshold
high_speed_mask = features["avg_speed_implausible"]

# Compare high-speed records against all other records
high_speed_group = features.loc[high_speed_mask]
normal_speed_group = features.loc[~high_speed_mask]

hdop_cols = [
    "raw_hdop_mean",
    "raw_hdop_median",
    "raw_hdop_max",
]

print("High-average-speed records:", len(high_speed_group))
print("Other records:", len(normal_speed_group))

print("\nHDOP summary: high-average-speed records")
display(high_speed_group[hdop_cols].describe())

print("\nHDOP summary: other records")
display(normal_speed_group[hdop_cols].describe())

High-average-speed records: 236
Other records: 151362

HDOP summary: high-average-speed records

       raw_hdop_mean  raw_hdop_median  raw_hdop_max
count     236.000000       236.000000    236.000000
mean        1.315013         1.238559      5.510593
std         1.714602         1.677795      5.343894
min         0.428761         0.400000      0.700000
25%         0.678919         0.700000      1.700000
50%         0.922288         0.800000      2.800000
75%         1.271996         1.200000      8.025000
max        13.122917        14.300000     17.000000

HDOP summary: other records

       raw_hdop_mean  raw_hdop_median   raw_hdop_max
count  151353.000000    151353.000000  151353.000000
mean        1.157421         1.033635       5.055808
std         1.136199         1.027048       5.327049
min         0.200000         0.200000       0.200000
25%         0.605851         0.600000       1.300000
50%         0.813792         0.800000       2.400000
75%         1.271955         1.100000       7.000000
max        16.900000        16.900000      17.000000

In [16]:
# Separate extreme-average-speed records from all other records
high_speed_group = features.loc[
    features["avg_speed_implausible"]
].copy()

normal_speed_group = features.loc[
    ~features["avg_speed_implausible"]
].copy()

signal_cols = [
    "n_signal_loss",
    "d_signal_loss",
    "r_signal_loss",
]

print("Extreme-average-speed records:", len(high_speed_group))
print("Other records:", len(normal_speed_group))

print("\nSignal-loss summary: extreme-average-speed records")
display(high_speed_group[signal_cols].describe())

print("\nSignal-loss summary: other records")
display(normal_speed_group[signal_cols].describe())

Extreme-average-speed records: 236
Other records: 151362

Signal-loss summary: extreme-average-speed records

       n_signal_loss  d_signal_loss  r_signal_loss
count     236.000000     236.000000     236.000000
mean   -26998.487288    2157.728814       0.032380
std     28664.512689    6434.960215       0.125310
min   -126712.000000       0.000000       0.000000
25%    -42870.750000       1.000000       0.000017
50%    -25717.000000      94.000000       0.001865
75%         0.000000     873.750000       0.009054
max     45327.000000   43023.000000       0.999830

Signal-loss summary: other records

       n_signal_loss  d_signal_loss  r_signal_loss
count  151313.000000  151313.000000  149648.000000
mean     1164.753293     195.408722       0.041213
std     10371.455589    1367.569884       5.264797
min   -150494.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000
50%         1.000000       0.000000       0.000000
75%         5.000000       1.000000       0.000034
max    532659.000000   67936.000000    1495.000000

In [17]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd().parent
SPEED_ROOT = PROJECT_ROOT / "data" / "raw" / "speed"

# Select the 236 tracks already flagged by our 120 km/h threshold
extreme_tracks = features.loc[
    features["avg_speed_implausible"],
    ["vehicle_id", "track_id", "avg_speed", "max_speed",
     "distance", "duration_seconds", "n_signal_loss",
     "d_signal_loss", "r_signal_loss"]
].copy()

print("Extreme-speed tracks:", len(extreme_tracks))

Extreme-speed tracks: 236

In [18]:
def inspect_track_telemetry(vehicle_id, track_id):
    path = SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"

    if not path.exists():
        return {"vehicle_id": vehicle_id, "track_id": track_id,
                "file_found": False}

    raw = pd.read_csv(path)

    # Identify timestamp column
    timestamp_candidates = [
        c for c in raw.columns
        if c.lower() in {"epoch", "timestamp", "time", "datetime"}
    ]

    speed_candidates = [
        c for c in raw.columns
        if c.lower() in {"speed", "velocity"}
    ]

    if len(timestamp_candidates) != 1 or len(speed_candidates) != 1:
        raise ValueError(
            f"Cannot identify timestamp/speed columns in {path}. "
            f"Columns: {raw.columns.tolist()}"
        )

    timestamp_col = timestamp_candidates[0]
    speed_col = speed_candidates[0]

    ts = pd.to_numeric(raw[timestamp_col], errors="coerce")
    valid_ts = ts.dropna().sort_values()

    gaps = valid_ts.diff().dropna()

    return {
        "vehicle_id": vehicle_id,
        "track_id": track_id,
        "file_found": True,
        "raw_observations": len(raw),
        "valid_timestamps": len(valid_ts),
        "max_gap_seconds": gaps.max() if len(gaps) else np.nan,
        "median_gap_seconds": gaps.median() if len(gaps) else np.nan,
        "gaps_over_10s": (gaps > 10).sum(),
        "gaps_over_60s": (gaps > 60).sum(),
        "missing_speed_values": raw[speed_col].isna().sum(),
        "raw_speed_min": pd.to_numeric(
            raw[speed_col], errors="coerce"
        ).min(),
        "raw_speed_max": pd.to_numeric(
            raw[speed_col], errors="coerce"
        ).max(),
    }

gap_results = pd.DataFrame([
    inspect_track_telemetry(row.vehicle_id, row.track_id)
    for row in extreme_tracks.itertuples(index=False)
])

display(
    gap_results.sort_values(
        "max_gap_seconds", ascending=False
    ).head(30)
)

,vehicle_id,track_id,file_found,raw_observations,valid_timestamps,max_gap_seconds,median_gap_seconds,gaps_over_10s,gaps_over_60s,missing_speed_values,raw_speed_min,raw_speed_max
6,2,3896,True,72,72,145.048,0.102,1,1,0,0.01,58.07
3,2,2611,True,81,81,110.089,0.102,1,1,0,0.02,45.29
147,76,129424,True,16148,16148,102.653,0.101,1,1,0,0.00,10.68
212,147,146549,True,20893,20893,96.745,0.101,3,1,0,0.01,26.12
44,50,97306,True,55607,55607,89.383,0.102,1,1,0,0.00,25.85
4,2,2775,True,76,76,84.984,0.200,1,1,0,0.32,84.82
76,55,109011,True,46904,46904,74.506,0.102,13,2,0,0.00,26.10
77,55,109118,True,18557,18557,66.137,0.102,5,1,0,0.00,23.97
78,55,109198,True,12427,12427,61.041,0.102,3,1,0,0.00,25.23
57,54,104752,True,30398,30398,47.839,0.102,8,0,0,0.00,23.78
200,137,144139,True,14172,14172,40.191,0.101,1,0,0,0.00,25.48
198,137,143930,True,21524,21524,37.972,0.101,2,0,0,0.00,25.53
113,59,117506,True,18641,18641,36.179,0.102,5,0,0,0.00,8.89
60,54,105456,True,17215,17215,34.562,0.102,4,0,0,0.00,23.26
112,59,117452,True,13435,13435,31.920,0.102,3,0,0,0.00,24.01
32,35,74847,True,30231,30231,30.312,0.102,8,0,0,0.00,9.61
111,59,116713,True,9908,9908,26.793,0.102,2,0,0,0.00,23.12
31,35,74467,True,6631,6631,26.736,0.102,1,0,0,0.00,0.20
53,54,104436,True,23680,23680,26.545,0.102,6,0,0,0.00,24.80
54,54,104509,True,9572,9572,26.518,0.102,2,0,0,0.00,9.78
24,22,50650,True,10244,10244,26.425,0.102,2,0,0,0.00,20.56
55,54,104625,True,3945,3945,25.927,0.102,1,0,0,0.00,0.29
100,58,114502,True,20688,20688,24.535,0.102,6,0,0,0.00,25.84
119,61,118848,True,17973,17973,22.180,0.102,1,0,0,0.00,18.07
26,24,53722,True,75177,75177,13.144,0.102,2,0,0,0.00,25.88
73,55,108354,True,22595,22595,10.974,0.102,1,0,0,0.00,25.80
75,55,108639,True,8229,8229,10.754,0.102,2,0,0,0.00,18.19
74,55,108447,True,6633,6633,10.166,0.102,1,0,0,0.00,10.75
70,55,107997,True,12682,12682,9.781,0.102,0,0,0,0.00,24.83
23,22,49984,True,10835,10835,9.032,0.102,0,0,0,0.00,11.58

In [19]:
def inspect_largest_gap(vehicle_id, track_id):
    path = SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"

    raw = pd.read_csv(path)

    timestamp_col = next(
        c for c in raw.columns
        if c.lower() in {"epoch", "timestamp", "time", "datetime"}
    )
    speed_col = next(
        c for c in raw.columns
        if c.lower() in {"speed", "velocity"}
    )

    raw = raw.copy()
    raw["_timestamp"] = pd.to_numeric(
        raw[timestamp_col], errors="coerce"
    )
    raw["_speed"] = pd.to_numeric(
        raw[speed_col], errors="coerce"
    )

    raw = raw.dropna(subset=["_timestamp"]).sort_values("_timestamp")
    raw["_gap"] = raw["_timestamp"].diff()

    gap_idx = raw["_gap"].idxmax()
    position = raw.index.get_loc(gap_idx)

    # Return observations around the largest gap
    return raw.iloc[
        max(0, position - 3): min(len(raw), position + 4)
    ][[timestamp_col, speed_col, "_gap"]]


# Inspect the five tracks with the largest gaps
top_gap_tracks = gap_results.nlargest(5, "max_gap_seconds")

for row in top_gap_tracks.itertuples(index=False):
    print(
        f"\nVehicle {row.vehicle_id}, track {row.track_id}, "
        f"maximum gap {row.max_gap_seconds:.3f} seconds"
    )
    display(inspect_largest_gap(row.vehicle_id, row.track_id))

Vehicle 2, track 3896, maximum gap 145.048 seconds

          epoch  speed     _gap
1  1.641553e+09  57.95    0.102
2  1.641553e+09  57.80    0.102
3  1.641553e+09  50.38    6.396
4  1.641553e+09   1.01  145.048
5  1.641553e+09   1.02    0.201
6  1.641553e+09   1.14    0.200
7  1.641553e+09   1.45    0.200

Vehicle 2, track 2611, maximum gap 110.089 seconds

           epoch  speed     _gap
51  1.631380e+09  36.25    0.165
52  1.631380e+09  36.14    0.198
53  1.631380e+09  35.98    0.102
54  1.631380e+09   0.32  110.089
55  1.631380e+09   0.28    0.102
56  1.631380e+09   0.30    0.102
57  1.631380e+09   0.24    0.102

Vehicle 76, track 129424, maximum gap 102.653 seconds

              epoch  speed     _gap
15822  1.702914e+09   0.02    0.101
15823  1.702914e+09   0.04    0.101
15824  1.702914e+09   0.00    0.102
15825  1.702914e+09   0.83  102.653
15826  1.702914e+09   0.84    0.101
15827  1.702914e+09   0.84    0.101
15828  1.702914e+09   0.75    0.101

Vehicle 147, track 146549, maximum gap 96.745 seconds

            epoch  speed    _gap
231  1.695968e+09  17.43   0.101
232  1.695968e+09  17.40   0.101
233  1.695968e+09  17.41   0.101
234  1.695968e+09  11.20  96.745
235  1.695968e+09  11.16   0.101
236  1.695968e+09  11.12   0.101
237  1.695968e+09  11.11   0.101

Vehicle 50, track 97306, maximum gap 89.383 seconds

              epoch  speed    _gap
40099  1.644851e+09  17.27   0.102
40100  1.644851e+09  17.52   0.101
40101  1.644851e+09  17.75   0.101
40102  1.644851e+09  20.15  89.383
40103  1.644851e+09  20.15   0.102
40104  1.644851e+09  20.14   0.102
40105  1.644851e+09  20.17   0.102

In [20]:
extreme_tracks = features.loc[
    features["avg_speed_implausible"],
    [
        "vehicle_id",
        "track_id",
        "duration_seconds",
        "avg_speed",
        "distance",
        "telemetry_span_seconds",
    ],
].copy()

extreme_tracks["duration_minus_telemetry_span"] = (
    extreme_tracks["duration_seconds"]
    - extreme_tracks["telemetry_span_seconds"]
)

extreme_tracks["telemetry_coverage_ratio"] = (
    extreme_tracks["telemetry_span_seconds"]
    / extreme_tracks["duration_seconds"].where(
        extreme_tracks["duration_seconds"] > 0
    )
)

display(
    extreme_tracks[
        [
            "duration_seconds",
            "telemetry_span_seconds",
            "duration_minus_telemetry_span",
            "telemetry_coverage_ratio",
        ]
    ].describe(percentiles=[0.25, 0.5, 0.75, 0.9])
)

display(
    extreme_tracks.sort_values(
        "telemetry_coverage_ratio",
        ascending=True,
    ).head(15)
)

,duration_seconds,telemetry_span_seconds,duration_minus_telemetry_span,telemetry_coverage_ratio
count,236.000000,236.000000,236.000000,236.000000
mean,1513.978945,1507.315373,6.663572,0.993648
std,1291.025872,1287.407197,56.717131,0.031807
min,0.613000,0.610000,0.001000,0.674405
25%,580.825750,579.474000,0.002750,0.999766
50%,1275.242000,1266.521500,0.004000,0.999996
75%,2061.248250,2061.247250,0.175500,0.999998
90%,3011.671500,2983.794000,3.467000,0.999999
max,7799.818000,7798.692000,847.655000,1.000000

,vehicle_id,track_id,duration_seconds,avg_speed,distance,telemetry_span_seconds,duration_minus_telemetry_span,telemetry_coverage_ratio
2775,2,2775,151.148,38.80,5865.0,101.935,49.213,0.674405
146549,147,146549,3106.575,38.45,119445.0,2258.920,847.655,0.727142
3851,2,3851,5.609,59.01,331.0,4.790,0.819,0.853985
142503,132,142503,1435.394,43.48,62418.0,1259.482,175.912,0.877447
3896,2,3896,179.070,61.46,11005.0,160.636,18.434,0.897057
144915,140,144915,409.024,172.13,70406.0,377.011,32.013,0.921733
138899,118,138899,158.683,740.79,117550.0,147.029,11.654,0.926558
124857,64,124857,56.763,34.62,1965.0,54.438,2.325,0.959040
122402,63,122402,128.656,224.80,28922.0,123.843,4.813,0.962590
144139,137,144139,1528.416,72.50,110807.0,1476.096,52.320,0.965768
146463,147,146463,1691.342,48.33,81739.0,1636.742,54.600,0.967718
2611,2,2611,125.462,46.75,5865.0,121.429,4.033,0.967855
138274,114,138274,225.400,1230.79,277421.0,220.653,4.747,0.978940
143430,135,143430,1867.709,43.59,81420.0,1833.979,33.730,0.981940
105456,54,105456,1894.415,45.48,86153.0,1867.389,27.026,0.985734

In [21]:
import numpy as np
import pandas as pd

# Select the 236 extreme-average-speed tracks
extreme_tracks = features.loc[
    features["avg_speed_implausible"],
    [
        "vehicle_id",
        "track_id",
        "distance",
        "avg_speed",
        "duration_seconds",
        "d_signal_loss",
        "r_signal_loss",
    ],
].copy()

# Ensure numeric values
for col in [
    "distance",
    "avg_speed",
    "duration_seconds",
    "d_signal_loss",
    "r_signal_loss",
]:
    extreme_tracks[col] = pd.to_numeric(
        extreme_tracks[col], errors="coerce"
    )

# Calculate signal-loss distance as a fraction of total distance
extreme_tracks["signal_loss_distance_fraction"] = (
    extreme_tracks["d_signal_loss"]
    / extreme_tracks["distance"].where(extreme_tracks["distance"] > 0)
)

# Convert to percentage for easier interpretation
extreme_tracks["signal_loss_distance_pct"] = (
    extreme_tracks["signal_loss_distance_fraction"] * 100
)

# Inspect the most extreme average speeds
display(
    extreme_tracks.sort_values("avg_speed", ascending=False)
    .head(20)
    .round(4)
)

,vehicle_id,track_id,distance,avg_speed,duration_seconds,d_signal_loss,r_signal_loss,signal_loss_distance_fraction,signal_loss_distance_pct
138274,114,138274,277421.0,1230.79,225.400,0.0,0.0000,0.0000,0.0000
49132,22,49132,182083.0,1121.26,162.391,983.0,0.0054,0.0054,0.5399
135017,102,135017,68080.0,1045.18,65.137,94.0,0.0014,0.0014,0.1381
102170,54,102170,17535.0,1042.82,16.815,50.0,0.0029,0.0029,0.2851
93407,48,93407,104576.0,765.12,136.679,41.0,0.0004,0.0004,0.0392
9707,5,9707,12865.0,764.73,16.823,0.0,0.0000,0.0000,0.0000
138899,118,138899,117550.0,740.79,158.683,0.0,0.0000,0.0000,0.0000
91783,47,91783,226810.0,662.91,342.144,1525.0,0.0067,0.0067,0.6724
143352,135,143352,106570.0,648.66,164.292,2.0,0.0000,0.0000,0.0019
150232,159,150232,88133.0,635.17,138.754,0.0,0.0000,0.0000,0.0000
104890,54,104890,39176.0,510.39,76.757,2.0,0.0001,0.0001,0.0051
114748,59,114748,149795.0,486.49,307.913,0.0,0.0000,0.0000,0.0000
103102,54,103102,99819.0,467.00,213.747,0.0,0.0000,0.0000,0.0000
29944,15,29944,269965.0,429.41,628.694,66.0,0.0002,0.0002,0.0244
105234,54,105234,114082.0,404.22,282.228,0.0,0.0000,0.0000,0.0000
61101,27,61101,92787.0,401.96,230.837,0.0,0.0000,0.0000,0.0000
132992,92,132992,69171.0,311.01,222.405,255.0,0.0037,0.0037,0.3687
131935,88,131935,75433.0,297.83,253.273,0.0,0.0000,0.0000,0.0000
146128,146,146128,62017.0,271.14,228.730,0.0,0.0000,0.0000,0.0000
11767,6,11767,170415.0,267.86,636.205,716.0,0.0042,0.0042,0.4202

In [22]:
fraction = extreme_tracks["signal_loss_distance_fraction"]

print("Valid fraction records:", fraction.notna().sum())
print("Invalid or missing:", fraction.isna().sum())
print("Fraction above 1:", (fraction > 1).sum())

display(
    (fraction[fraction.between(0, 1)])
    .describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95])
    .to_frame("signal_loss_distance_fraction")
)

print(
    "Tracks with signal-loss distance above 10% of total distance:",
    (fraction > 0.10).sum(),
)

Valid fraction records: 236
Invalid or missing: 0
Fraction above 1: 0

       signal_loss_distance_fraction
count                     236.000000
mean                        0.032380
std                         0.125310
min                         0.000000
25%                         0.000017
50%                         0.001865
75%                         0.009054
90%                         0.068496
95%                         0.146200
max                         0.999829

Tracks with signal-loss distance above 10% of total distance: 17

In [23]:
import numpy as np
import pandas as pd

def estimate_distance_from_speed(vehicle_id, track_id):
    path = SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"

    try:
        raw = pd.read_csv(path)
        epoch_col = next(
            c for c in raw.columns
            if c.lower() in {"epoch", "timestamp", "time", "datetime"}
        )
        speed_col = next(
            c for c in raw.columns
            if c.lower() in {"speed", "velocity"}
        )

        raw["_t"] = pd.to_numeric(raw[epoch_col], errors="coerce")
        raw["_v"] = pd.to_numeric(raw[speed_col], errors="coerce")
        raw = (
            raw.dropna(subset=["_t", "_v"])
            .sort_values("_t")
            .drop_duplicates("_t")
        )

        dt = raw["_t"].diff().to_numpy()
        speed = raw["_v"].to_numpy()

        # Integrate only across short gaps (at most 1 second).
        valid = (
            np.isfinite(dt)
            & (dt > 0)
            & (dt <= 1.0)
            & np.isfinite(speed)
        )

        # Trapezoidal integration: mean speed × elapsed time.
        estimated_distance = np.sum(
            ((speed[1:] + speed[:-1]) / 2)[valid[1:]]
            * dt[valid[1:]]
        )

        covered_seconds = dt[valid].sum()

        return {
            "vehicle_id": vehicle_id,
            "track_id": track_id,
            "raw_speed_integrated_distance_m": estimated_distance,
            "speed_integrated_seconds": covered_seconds,
            "raw_observations_used": int(valid.sum()),
        }

    except (OSError, ValueError, StopIteration, KeyError):
        return {
            "vehicle_id": vehicle_id,
            "track_id": track_id,
            "raw_speed_integrated_distance_m": np.nan,
            "speed_integrated_seconds": np.nan,
            "raw_observations_used": 0,
        }


# Run for all 236 extreme-speed tracks.
distance_checks = pd.DataFrame([
    estimate_distance_from_speed(row.vehicle_id, row.track_id)
    for row in extreme_tracks.itertuples(index=False)
])

distance_checks = distance_checks.merge(
    extreme_tracks[
        ["vehicle_id", "track_id", "distance",
         "avg_speed", "duration_seconds"]
    ],
    on=["vehicle_id", "track_id"],
    how="left",
)

distance_checks["recorded_to_integrated_ratio"] = (
    distance_checks["distance"]
    / distance_checks["raw_speed_integrated_distance_m"].replace(0, np.nan)
)

display(
    distance_checks.sort_values(
        "recorded_to_integrated_ratio",
        ascending=False,
    ).head(20).round(3)
)

IndexError: boolean index did not match indexed array along axis 0; size of axis is 8062 but size of corresponding boolean axis is 8061

In [24]:

def estimate_distance_from_speed(vehicle_id, track_id):
    path = SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"

    try:
        raw = pd.read_csv(path)

        epoch_col = next(
            c for c in raw.columns
            if c.lower() in {"epoch", "timestamp", "time", "datetime"}
        )
        speed_col = next(
            c for c in raw.columns
            if c.lower() in {"speed", "velocity"}
        )

        raw["_t"] = pd.to_numeric(raw[epoch_col], errors="coerce")
        raw["_v"] = pd.to_numeric(raw[speed_col], errors="coerce")

        raw = (
            raw.dropna(subset=["_t", "_v"])
            .sort_values("_t")
            .drop_duplicates("_t")
        )

        t = raw["_t"].to_numpy()
        v = raw["_v"].to_numpy()

        # One time interval between each consecutive pair of observations
        dt = np.diff(t)

        # Keep only short, positive intervals
        valid = (
            np.isfinite(dt)
            & (dt > 0)
            & (dt <= 1.0)
            & np.isfinite(v[:-1])
            & np.isfinite(v[1:])
        )

        # Trapezoidal integration over valid intervals
        interval_speed = (v[:-1] + v[1:]) / 2

        estimated_distance = np.sum(
            interval_speed[valid] * dt[valid]
        )

        covered_seconds = dt[valid].sum()

        return {
            "vehicle_id": vehicle_id,
            "track_id": track_id,
            "raw_speed_integrated_distance_m": estimated_distance,
            "speed_integrated_seconds": covered_seconds,
            "raw_observations_used": int(valid.sum()),
        }

    except (OSError, ValueError, StopIteration, KeyError):
        return {
            "vehicle_id": vehicle_id,
            "track_id": track_id,
            "raw_speed_integrated_distance_m": np.nan,
            "speed_integrated_seconds": np.nan,
            "raw_observations_used": 0,
        }

In [25]:
distance_checks = pd.DataFrame([
    estimate_distance_from_speed(row.vehicle_id, row.track_id)
    for row in extreme_tracks.itertuples(index=False)
])

distance_checks = distance_checks.merge(
    extreme_tracks[
        ["vehicle_id", "track_id", "distance",
         "avg_speed", "duration_seconds"]
    ],
    on=["vehicle_id", "track_id"],
    how="left",
)

distance_checks["recorded_to_integrated_ratio"] = (
    distance_checks["distance"]
    / distance_checks["raw_speed_integrated_distance_m"].replace(0, np.nan)
)

display(
    distance_checks.sort_values(
        "recorded_to_integrated_ratio",
        ascending=False,
    ).head(20).round(3)
)

,vehicle_id,track_id,raw_speed_integrated_distance_m,speed_integrated_seconds,raw_observations_used,distance,avg_speed,duration_seconds,recorded_to_integrated_ratio
45,54,102170,0.391,16.811,165,17535.0,1042.82,16.815,44880.983
40,48,93407,3.074,136.675,1341,104576.0,765.12,136.679,34019.518
9,5,9707,0.433,16.820,165,12865.0,764.73,16.823,29730.541
102,59,114748,7.039,307.910,3021,149795.0,486.49,307.913,21280.147
11,6,11767,15.303,633.125,6212,170415.0,267.86,636.205,11136.019
31,35,74467,17.247,676.318,6629,137462.0,195.52,703.058,7970.239
16,12,25036,4.798,196.618,1929,31717.0,161.31,196.622,6611.117
46,54,102213,45.139,2020.241,19821,268164.0,132.74,2020.244,5940.806
207,146,146128,10.973,228.729,2265,62017.0,271.14,228.730,5651.972
18,17,37770,6.241,299.321,2937,31964.0,106.79,299.324,5121.894
63,55,106751,16.240,667.380,6548,79796.0,119.23,669.285,4913.535
92,57,112214,14.058,607.511,5961,63318.0,104.23,607.514,4504.204
49,54,103102,24.327,213.744,2097,99819.0,467.00,213.747,4103.203
15,12,24714,18.093,932.889,9152,73002.0,77.60,940.773,4034.928
145,75,129171,22.402,924.222,9150,79521.0,86.04,924.224,3549.690
27,26,58485,4.805,273.669,2685,14764.0,53.95,273.672,3072.917
167,96,133866,48.341,1275.830,12634,146838.0,114.99,1276.919,3037.535
30,28,63306,7.447,299.342,2937,22190.0,74.13,299.347,2979.625
55,54,104625,11.385,401.865,3943,32663.0,76.35,427.796,2869.047
37,46,88493,0.495,17.119,164,1339.0,78.20,17.123,2705.515

In [26]:
top_cases = distance_checks.nlargest(
    5, "recorded_to_integrated_ratio"
)

display(
    top_cases[
        [
            "vehicle_id",
            "track_id",
            "distance",
            "avg_speed",
            "duration_seconds",
            "raw_speed_integrated_distance_m",
            "speed_integrated_seconds",
            "recorded_to_integrated_ratio",
        ]
    ].round(4)
)

for row in top_cases.itertuples(index=False):
    path = SPEED_ROOT / str(row.vehicle_id) / f"{row.track_id}.csv"
    raw = pd.read_csv(path)

    speed_col = next(
        c for c in raw.columns
        if c.lower() in {"speed", "velocity"}
    )

    speed = pd.to_numeric(raw[speed_col], errors="coerce").dropna()

    print(
        f"\nVehicle {row.vehicle_id}, track {row.track_id}"
        f"\nRaw speed statistics (original units):"
    )
    print(speed.describe(percentiles=[0.5, 0.9, 0.99]))

,vehicle_id,track_id,distance,avg_speed,duration_seconds,raw_speed_integrated_distance_m,speed_integrated_seconds,recorded_to_integrated_ratio
45,54,102170,17535.0,1042.82,16.815,0.3907,16.811,44880.9831
40,48,93407,104576.0,765.12,136.679,3.0740,136.675,34019.5185
9,5,9707,12865.0,764.73,16.823,0.4327,16.820,29730.5407
102,59,114748,149795.0,486.49,307.913,7.0392,307.910,21280.1472
11,6,11767,170415.0,267.86,636.205,15.3030,633.125,11136.0190

Vehicle 54, track 102170
Raw speed statistics (original units):
count    166.000000
mean       0.023193
std        0.013531
min        0.000000
50%        0.020000
90%        0.040000
99%        0.060000
max        0.070000
Name: speed, dtype: float64

Vehicle 48, track 93407
Raw speed statistics (original units):
count    1342.000000
mean        0.022481
std         0.012023
min         0.000000
50%         0.020000
90%         0.040000
99%         0.055900
max         0.090000
Name: speed, dtype: float64

Vehicle 5, track 9707
Raw speed statistics (original units):
count    166.000000
mean       0.025843
std        0.012512
min        0.000000
50%        0.020000
90%        0.040000
99%        0.060000
max        0.070000
Name: speed, dtype: float64

Vehicle 59, track 114748
Raw speed statistics (original units):
count    3022.000000
mean        0.022862
std         0.027706
min         0.000000
50%         0.020000
90%         0.040000
99%         0.070000
max         0.950000
Name: speed, dtype: float64

Vehicle 6, track 11767
Raw speed statistics (original units):
count    6214.000000
mean        0.024171
std         0.015111
min         0.000000
50%         0.020000
90%         0.040000
99%         0.070000
max         0.130000
Name: speed, dtype: float64

In [27]:
top5 = distance_checks.nlargest(
    5, "recorded_to_integrated_ratio"
)[["vehicle_id", "track_id"]]

signal_fields = features[
    [
        "vehicle_id",
        "track_id",
        "distance",
        "avg_speed",
        "n_signal_loss",
        "d_signal_loss",
        "r_signal_loss",
    ]
]

top5_details = top5.merge(
    signal_fields,
    on=["vehicle_id", "track_id"],
    how="left",
)

top5_details["signal_loss_distance_fraction"] = (
    top5_details["d_signal_loss"]
    / top5_details["distance"].where(
        top5_details["distance"] > 0
    )
)

display(top5_details.round(5))

,vehicle_id,track_id,distance,avg_speed,n_signal_loss,d_signal_loss,r_signal_loss,signal_loss_distance_fraction
0,54,102170,17535.0,1042.82,-19062.0,50.0,0.00285,0.00285
1,48,93407,104576.0,765.12,-77615.0,41.0,0.00039,0.00039
2,5,9707,12865.0,764.73,0.0,0.0,0.00000,0.00000
3,59,114748,149795.0,486.49,-1226.0,0.0,0.00000,0.00000
4,6,11767,170415.0,267.86,-76395.0,716.0,0.00420,0.00420

In [28]:
features["speed_distance_validity"] = np.where(
    features["avg_speed"] > (120 / 3.6),
    "invalid",
    "valid"
)

In [32]:
n_loss = features["n_signal_loss_valid"].dropna()

q1 = n_loss.quantile(0.25)
q3 = n_loss.quantile(0.75)
upper_fence = q3 + 1.5 * (q3 - q1)

print("Upper fence:", upper_fence)
print("Observations above fence:", (n_loss > upper_fence).sum())
print("Percentage above fence:", (n_loss > upper_fence).mean() * 100)

display(
    features.loc[
        features["n_signal_loss_valid"] > upper_fence,
        [
            "vehicle_id",
            "track_id",
            "n_signal_loss_valid",
            "d_signal_loss",
            "r_signal_loss_valid",
            "distance_km",
            "duration_minutes",
        ],
    ]
    .sort_values("n_signal_loss_valid", ascending=False)
    .head(20)
)

Upper fence: 12.5
Observations above fence: 25499
Percentage above fence: 17.042279878627475

,vehicle_id,track_id,n_signal_loss_valid,d_signal_loss,r_signal_loss_valid,distance_km,duration_minutes
74784,35,74784,532659.0,246.0,0.012045,20.423,1029.733783
74708,35,74708,391263.0,3.0,0.000070,42.811,736.253283
63263,28,63263,211555.0,0.0,0.000000,213.189,363.094333
63830,29,63830,209251.0,0.0,0.000000,0.004,355.796783
52439,24,52439,205715.0,0.0,0.000000,249.634,351.395000
54541,25,54541,203732.0,0.0,0.000000,185.510,349.324100
130715,80,130715,200072.0,0.0,0.000000,0.578,352.143583
53439,24,53439,197234.0,0.0,0.000000,241.239,342.807500
139732,121,139732,195357.0,0.0,0.000000,233.692,342.031067
52186,24,52186,193783.0,0.0,0.000000,0.127,344.256700
89070,46,89070,190215.0,0.0,0.000000,0.003,324.432783
103559,54,103559,188258.0,0.0,0.000000,0.005,322.663833
63758,29,63758,188146.0,0.0,0.000000,0.019,320.672617
82436,41,82436,187516.0,0.0,0.000000,286.428,319.891283
145099,140,145099,186244.0,0.0,0.000000,1.721,327.236517
64585,30,64585,185985.0,0.0,0.000000,0.657,339.439300
133143,93,133143,185740.0,0.0,0.000000,0.360,317.571583
89125,46,89125,184683.0,0.0,0.000000,0.002,336.870033
52940,24,52940,184678.0,0.0,0.000000,238.355,330.285967
81959,41,81959,182733.0,0.0,0.000000,0.007,311.993600

In [42]:
signal_analysis = features[
    [
        "vehicle_id",
        "track_id",
        "n_signal_loss_valid",
        "distance_km",
        "duration_minutes",
    ]
].copy()

signal_analysis["signal_losses_per_hour"] = (
    signal_analysis["n_signal_loss_valid"]
    / (signal_analysis["duration_minutes"] / 60).where(
        signal_analysis["duration_minutes"] > 0
    )
)

signal_analysis["signal_losses_per_km"] = (
    signal_analysis["n_signal_loss_valid"]
    / signal_analysis["distance_km"].where(
        signal_analysis["distance_km"] > 0
    )
)

display(
    signal_analysis[
        ["signal_losses_per_hour", "signal_losses_per_km"]
    ].describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])
)

       signal_losses_per_hour  signal_losses_per_km
count           149613.000000          1.479590e+05
mean              1094.139578          3.911783e+04
std               5167.026149          1.020482e+06
min                  0.000000          0.000000e+00
25%                  0.000000          0.000000e+00
50%                  8.709305          3.560608e-01
75%                 20.419450          2.173913e+01
90%                353.171431          1.666667e+02
95%               2963.507389          5.782179e+02
99%              33346.554239          8.118477e+04
max              36562.142948          9.525800e+07

In [34]:
# Add relevant existing features to the temporary analysis dataframe
extra_cols = [
    "avg_speed_valid",
    "max_speed_valid",
    "avg_speed_kmh",
    "max_speed_kmh",
    "raw_speed_mean_kmh",
    "distance",
    "duration_seconds",
    "telemetry_span_seconds",
    "avg_hdop",
    "raw_hdop_mean",
    "raw_hdop_max",
    "d_signal_loss",
    "r_signal_loss_valid",
    "speed_distance_validity",
]

available_cols = [
    col for col in extra_cols
    if col in features.columns
]

signal_analysis = signal_analysis.join(
    features[available_cols].drop(
        columns=[
            col for col in available_cols
            if col in signal_analysis.columns
        ],
        errors="ignore",
    )
)

# Inspect the highest rates, with all relevant parameters
analysis_cols = [
    "vehicle_id",
    "track_id",
    "n_signal_loss_valid",
    "duration_minutes",
    "distance_km",
    "signal_losses_per_hour",
    "signal_losses_per_km",
    "avg_speed_kmh",
    "max_speed_kmh",
    "raw_speed_mean_kmh",
    "avg_hdop",
    "raw_hdop_mean",
    "d_signal_loss",
    "r_signal_loss_valid",
]

analysis_cols = [
    col for col in analysis_cols
    if col in signal_analysis.columns
]

print("Highest signal-loss rate per hour")
display(
    signal_analysis.sort_values(
        "signal_losses_per_hour",
        ascending=False,
    )[analysis_cols].head(20)
)

print("Highest signal-loss rate per kilometre")
display(
    signal_analysis.sort_values(
        "signal_losses_per_km",
        ascending=False,
    )[analysis_cols].head(20)
)

Highest signal-loss rate per hour

,vehicle_id,track_id,n_signal_loss_valid,duration_minutes,distance_km,signal_losses_per_hour,signal_losses_per_km,avg_speed_kmh,max_speed_kmh,raw_speed_mean_kmh,avg_hdop,raw_hdop_mean,d_signal_loss,r_signal_loss_valid
148834,155,148834,80.0,0.131283,0.000,36562.142948,NaN,0.000,16.524,10.719797,6.522412,6.487342,0.0,NaN
148839,155,148839,80.0,0.131300,0.000,36557.501904,NaN,0.000,3.600,1.975899,9.794562,9.726582,0.0,NaN
140666,126,140666,80.0,0.131300,0.000,36557.501904,NaN,0.000,0.900,0.457519,9.296662,9.243038,0.0,NaN
147277,149,147277,80.0,0.131317,0.000,36552.862038,NaN,0.000,4.752,4.015139,10.157312,10.144304,0.0,NaN
131598,83,131598,80.0,0.131317,0.000,36552.862038,NaN,0.000,5.184,2.327241,6.083662,6.089873,0.0,NaN
147208,149,147208,80.0,0.131317,0.000,36552.862038,NaN,0.000,1.332,0.826633,9.862787,9.834177,0.0,NaN
50805,23,50805,83.0,0.137633,0.000,36183.095180,NaN,0.000,60.768,53.758976,9.645699,9.650000,0.0,NaN
51212,23,51212,83.0,0.137650,0.000,36178.714130,NaN,0.000,3.384,1.733707,6.018217,6.023171,0.0,NaN
109287,56,109287,83.0,0.137667,0.000,36174.334140,NaN,0.000,1.008,0.360439,7.507928,7.429268,0.0,NaN
148292,153,148292,161.0,0.267617,0.000,36096.406552,NaN,0.000,2.952,0.870525,6.258118,6.242500,0.0,NaN
145784,144,145784,242.0,0.403950,0.000,35945.042703,NaN,0.000,2.484,0.859220,8.964855,8.947718,0.0,NaN
148649,155,148649,404.0,0.676600,0.000,35826.189772,NaN,0.000,8.424,2.759940,5.619488,5.619107,0.0,NaN
132372,90,132372,566.0,0.949350,0.000,35771.843893,NaN,0.000,3.888,2.219512,13.545889,13.552920,0.0,NaN
50002,22,50002,167.0,0.280317,0.000,35745.288067,NaN,0.000,3.168,1.428072,6.918461,6.897590,0.0,NaN
44402,20,44402,167.0,0.280367,0.000,35738.913328,NaN,0.000,2.448,0.790699,5.255952,5.246386,0.0,NaN
106119,54,106119,167.0,0.280450,0.000,35728.293814,NaN,0.000,5.328,2.199904,6.277605,6.272289,0.0,NaN
148946,156,148946,37942.0,63.818450,40.444,35671.815909,9.381367e+02,38.016,88.524,37.902641,1.329319,1.329400,0.0,0.0
145783,144,145783,4130.0,6.947633,0.000,35666.821795,NaN,0.000,8.856,1.700972,5.989730,5.989101,0.0,NaN
144795,139,144795,80.0,0.134667,0.000,35643.564356,NaN,0.000,13.680,12.560850,11.872388,11.877500,0.0,NaN
138490,116,138490,12306.0,20.717017,0.003,35640.266737,4.102000e+06,0.000,89.532,31.086056,0.892293,0.892941,0.0,0.0

Highest signal-loss rate per kilometre

,vehicle_id,track_id,n_signal_loss_valid,duration_minutes,distance_km,signal_losses_per_hour,signal_losses_per_km,avg_speed_kmh,max_speed_kmh,raw_speed_mean_kmh,avg_hdop,raw_hdop_mean,d_signal_loss,r_signal_loss_valid
96369,50,96369,95258.0,163.923067,0.001,34866.844040,9.525800e+07,0.0,92.412,60.559467,0.519190,0.519422,0.0,0.0
89125,46,89125,184683.0,336.870033,0.002,32893.932091,9.234150e+07,0.0,95.364,39.089943,3.275453,3.275663,0.0,0.0
144443,138,144443,90649.0,186.929550,0.001,29096.202286,9.064900e+07,0.0,93.636,65.944269,0.923286,0.923046,0.0,0.0
88172,45,88172,170577.0,293.284100,0.002,34896.607078,8.528850e+07,0.0,97.164,64.359447,0.505038,0.505506,0.0,0.0
90421,46,90421,77698.0,137.436200,0.001,33920.320847,7.769800e+07,0.0,90.576,65.402554,0.569405,0.568237,0.0,0.0
605,1,605,153893.0,262.058400,0.002,35234.817888,7.694650e+07,0.0,92.484,54.197642,0.799543,0.799994,0.0,0.0
92929,48,92929,68293.0,117.338833,0.001,34920.919900,6.829300e+07,0.0,95.184,78.489194,0.926251,0.926140,0.0,0.0
89070,46,89070,190215.0,324.432783,0.003,35178.010936,6.340500e+07,0.0,0.792,0.086034,0.555277,0.555904,0.0,0.0
87936,45,87936,125383.0,215.151367,0.002,34965.987512,6.269150e+07,0.0,95.328,81.774400,0.687836,0.688758,0.0,0.0
82820,41,82820,62076.0,108.928250,0.001,34192.782864,6.207600e+07,0.0,91.188,71.862011,0.685902,0.686024,0.0,0.0
93896,49,93896,119805.0,205.554567,0.002,34970.276343,5.990250e+07,0.0,95.184,71.102828,0.777103,0.777473,0.0,0.0
41393,19,41393,52920.0,90.553200,0.001,35064.470389,5.292000e+07,0.0,41.616,1.731570,1.093925,1.096472,0.0,0.0
63830,29,63830,209251.0,355.796783,0.004,35287.165562,5.231275e+07,0.0,71.964,10.778961,0.542397,0.541862,0.0,0.0
90217,46,90217,153137.0,262.531917,0.003,34998.487485,5.104567e+07,0.0,90.612,67.472849,0.531412,0.531682,0.0,0.0
105152,54,105152,50891.0,93.239750,0.001,32748.479055,5.089100e+07,0.0,77.040,49.228045,1.418929,1.419226,0.0,0.0
87531,44,87531,96245.0,165.820983,0.002,34824.905051,4.812250e+07,0.0,94.248,53.964558,0.499064,0.498821,0.0,0.0
120091,62,120091,45187.0,77.071050,0.001,35178.189476,4.518700e+07,0.0,75.492,32.534114,0.578653,0.577014,0.0,0.0
90909,47,90909,88917.0,152.414283,0.002,35003.412300,4.445850e+07,0.0,92.484,58.807161,0.734979,0.735960,0.0,0.0
92770,48,92770,132767.0,228.347283,0.003,34885.547503,4.425567e+07,0.0,94.788,75.649080,0.705321,0.705498,0.0,0.0
118956,61,118956,86860.0,149.022800,0.002,34971.829814,4.343000e+07,0.0,103.932,52.271051,0.650528,0.649774,0.0,0.0

In [40]:
features["signal_loss_validity"] = np.where(
    (features["avg_speed_valid"] == 0)
    & (features["distance"] == 0)
    & (features["n_signal_loss_valid"] >= 13),
    "invalid",
    "valid"
)

In [37]:
features["signal_loss_validity"].value_counts()

signal_loss_validity
valid      151307
invalid       291
Name: count, dtype: int64

In [38]:
features.loc[
    features["track_id"] == 148946,
    [
        "vehicle_id",
        "track_id",
        "distance",
        "avg_speed",
        "max_speed",
        "n_signal_loss",
        "d_signal_loss",
        "r_signal_loss",
        "duration_seconds",
        "telemetry_span_seconds",
        "avg_hdop",
        "raw_hdop_mean",
        "raw_hdop_max"
    ]
].to_string(index=False)

' vehicle_id  track_id  distance  avg_speed  max_speed  n_signal_loss  d_signal_loss  r_signal_loss  duration_seconds  telemetry_span_seconds  avg_hdop  raw_hdop_mean  raw_hdop_max\n        156    148946   40444.0      10.56      24.59        37942.0            0.0            0.0          3829.107                 3829.02  1.329319         1.3294           2.4'

In [43]:
features.loc[
    (features["n_signal_loss_valid"] >= 13)
    & (features["distance"] > 0)
    & (features["avg_speed_valid"] > 0),
    [
        "vehicle_id",
        "track_id",
        "distance",
        "avg_speed",
        "n_signal_loss",
        "d_signal_loss",
        "r_signal_loss",
        "duration_seconds",
        "avg_hdop",
        "raw_hdop_mean"
    ]
].sort_values(
    "n_signal_loss_valid",
    ascending=False
).head(20).to_string(index=False)

KeyError: 'n_signal_loss_valid'

In [44]:
features.loc[
    (features["n_signal_loss"] >= 13)
    & (features["distance"] > 0)
    & (features["avg_speed"] > 0),
    [
        "vehicle_id",
        "track_id",
        "distance",
        "avg_speed",
        "n_signal_loss",
        "d_signal_loss",
        "r_signal_loss",
        "duration_seconds",
        "avg_hdop",
        "raw_hdop_mean"
    ]
].sort_values(
    "n_signal_loss",
    ascending=False
).head(20).to_string(index=False)

' vehicle_id  track_id  distance  avg_speed  n_signal_loss  d_signal_loss  r_signal_loss  duration_seconds  avg_hdop  raw_hdop_mean\n         35     74784   20423.0       0.33       532659.0          246.0       0.012045         61784.027  0.950729       0.951498\n         35     74708   42811.0       0.97       391263.0            3.0       0.000070         44175.197  0.693506       0.694492\n         28     63263  213189.0       9.79       211555.0            0.0       0.000000         21785.660  0.816891       0.817117\n         24     52439  249634.0      11.84       205715.0            0.0       0.000000         21083.700  0.947259       0.947726\n         25     54541  185510.0       8.85       203732.0            0.0       0.000000         20959.446  0.676957       0.677285\n         80    130715     578.0       0.03       200072.0            0.0       0.000000         21128.615  0.658859       0.659911\n         24     53439  241239.0      11.73       197234.0            0.0       0.000000         20568.450  0.920359       0.920565\n        121    139732  233692.0      11.39       195357.0            0.0       0.000000         20521.864  1.463905       1.464100\n         24     52186     127.0       0.01       193783.0            0.0       0.000000         20655.402  0.786762       0.787783\n         41     82436  286428.0      14.92       187516.0            0.0       0.000000         19193.477  0.567263       0.567779\n        140    145099    1721.0       0.09       186244.0            0.0       0.000000         19634.191  1.054655       1.055528\n         30     64585     657.0       0.03       185985.0            0.0       0.000000         20366.358  0.488442       0.488689\n         93    133143     360.0       0.02       185740.0            0.0       0.000000         19054.295  0.803828       0.803466\n         24     52940  238355.0      12.03       184678.0            0.0       0.000000         19817.158  0.856937       0.857212\n         36     75952     381.0       0.02       182367.0            0.0       0.000000         19393.279  0.602419       0.603199\n         28     63174     264.0       0.01       181924.0            0.0       0.000000         19142.189  1.350859       1.350709\n         93    133132     516.0       0.03       181097.0            0.0       0.000000         18571.643  0.614339       0.613733\n         30     64633   52921.0       2.52       180594.0          635.0       0.011999         21011.521  0.516529       0.516194\n         24     53435  204302.0      11.04       179153.0            0.0       0.000000         18507.632  0.921705       0.922286\n         80    130675  264472.0      13.81       177486.0            1.0       0.000004         19152.188  0.653554       0.653618'

In [45]:
# Inspect the raw telemetry file for one extreme-count track
vehicle_id = 28
track_id = 63263

raw = pd.read_csv(
    SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"
)

print("Raw telemetry observations:", len(raw))

print(
    features.loc[
        features["track_id"] == track_id,
        [
            "vehicle_id",
            "track_id",
            "n_signal_loss",
            "duration_seconds",
            "telemetry_span_seconds",
            "distance",
            "d_signal_loss",
            "r_signal_loss"
        ]
    ].to_string(index=False)
)

Raw telemetry observations: 211593
 vehicle_id  track_id  n_signal_loss  duration_seconds  telemetry_span_seconds  distance  d_signal_loss  r_signal_loss
         28     63263       211555.0          21785.66               21785.657  213189.0            0.0            0.0

In [46]:
# Compare reported signal-loss counts with raw telemetry observations
track_ids_to_check = [63263, 52439, 54541, 74784, 74708]

for track_id in track_ids_to_check:
    row = features.loc[features["track_id"] == track_id].iloc[0]

    vehicle_id = int(row["vehicle_id"])
    path = SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"

    raw = pd.read_csv(path)

    print(
        f"Vehicle: {vehicle_id}, "
        f"Track: {track_id}, "
        f"Raw observations: {len(raw):,}, "
        f"Signal-loss count: {row['n_signal_loss']:,.0f}, "
        f"Difference: {len(raw) - row['n_signal_loss']:,.0f}"
    )

Vehicle: 28, Track: 63263, Raw observations: 211,593, Signal-loss count: 211,555, Difference: 38
Vehicle: 24, Track: 52439, Raw observations: 205,797, Signal-loss count: 205,715, Difference: 82
Vehicle: 25, Track: 54541, Raw observations: 203,732, Signal-loss count: 203,732, Difference: 0
Vehicle: 35, Track: 74784, Raw observations: 558,104, Signal-loss count: 532,659, Difference: 25,445
Vehicle: 35, Track: 74708, Raw observations: 399,057, Signal-loss count: 391,263, Difference: 7,794

In [47]:
vehicle_id = 28
track_id = 63263

raw = pd.read_csv(
    SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"
)

print("Columns:", raw.columns.tolist())
display(raw.head(10))
display(raw.tail(10))

print("\nMissing values:")
print(raw.isna().sum())

print("\nDuplicate rows:", raw.duplicated().sum())

Columns: ['epoch', 'speed', 'hdop']

          epoch  speed  hdop
0  1.646218e+09   0.07   1.2
1  1.646218e+09   0.04   1.2
2  1.646218e+09   0.01   1.2
3  1.646218e+09   0.06   1.1
4  1.646218e+09   0.05   1.1
5  1.646218e+09   0.07   1.1
6  1.646218e+09   0.04   1.1
7  1.646218e+09   0.03   1.1
8  1.646218e+09   0.07   1.1
9  1.646218e+09   0.10   1.1

               epoch  speed  hdop
211583  1.646239e+09   0.01   0.9
211584  1.646239e+09   0.02   0.9
211585  1.646239e+09   0.01   0.9
211586  1.646239e+09   0.04   0.9
211587  1.646239e+09   0.02   0.9
211588  1.646239e+09   0.03   0.9
211589  1.646239e+09   0.01   0.9
211590  1.646239e+09   0.03   0.9
211591  1.646239e+09   0.02   0.9
211592  1.646239e+09   0.01   0.9

Missing values:
epoch    0
speed    0
hdop     0
dtype: int64

Duplicate rows: 0

In [48]:
print(raw["speed"].describe(percentiles=[0.5, 0.9, 0.99]))
print("\nSpeed value counts:")
print(raw["speed"].value_counts().head(15))

count    211593.000000
mean          9.629955
std           8.706702
min           0.000000
50%          11.330000
90%          19.450000
99%          19.970000
max          21.330000
Name: speed, dtype: float64

Speed value counts:
speed
0.02     19062
0.03     15582
0.01     15510
0.04     11023
0.05      7104
0.06      4474
0.07      2689
0.00      2150
0.08      1692
19.33     1350
19.30     1298
19.31     1294
19.34     1283
19.32     1266
19.36     1257
Name: count, dtype: int64

In [49]:
vehicle_id = 28
track_id = 63263

raw = pd.read_csv(
    SPEED_ROOT / str(vehicle_id) / f"{track_id}.csv"
).sort_values("epoch").reset_index(drop=True)

# Count samples that fail the documented speed/HDOP criteria
quality_failure = (
    (raw["hdop"] >= 50)
    | (raw["speed"] < 1.388)
    | (raw["speed"] > 75)
)

# Inspect gaps in the raw timestamps
time_diff = raw["epoch"].diff()
median_period = time_diff[time_diff > 0].median()

large_gaps = time_diff >= 3 * median_period

reported_count = features.loc[
    (features["vehicle_id"] == vehicle_id)
    & (features["track_id"] == track_id),
    "n_signal_loss"
].iloc[0]

print(f"Raw observations: {len(raw):,}")
print(f"Reported signal-loss count: {reported_count:,.0f}")
print(f"Samples failing visible quality criteria: {quality_failure.sum():,}")
print(f"Median sampling interval: {median_period:.4f} seconds")
print(f"Large timestamp gaps: {large_gaps.sum():,}")

Raw observations: 211,593
Reported signal-loss count: 211,555
Samples failing visible quality criteria: 86,349
Median sampling interval: 0.1020 seconds
Large timestamp gaps: 68

In [50]:
print(
    "Observations below 1.388 m/s:",
    (raw["speed"] < 1.388).sum()
)

print(
    "Observations at or above 1.388 m/s:",
    (raw["speed"] >= 1.388).sum()
)

print(
    "Observations above 75 m/s:",
    (raw["speed"] > 75).sum()
)

print(
    "Observations with HDOP >= 50:",
    (raw["hdop"] >= 50).sum()
)

Observations below 1.388 m/s: 86349
Observations at or above 1.388 m/s: 125244
Observations above 75 m/s: 0
Observations with HDOP >= 50: 0

In [51]:
# Inspect extreme signal-loss counts among tracks with plausible movement
high_signal_loss_tracks = features.loc[
    (features["n_signal_loss"] >= 100_000)
    & (features["distance"] > 0)
    & (features["avg_speed"] > 0),
    [
        "vehicle_id",
        "track_id",
        "distance",
        "avg_speed",
        "max_speed",
        "n_signal_loss",
        "d_signal_loss",
        "r_signal_loss",
        "duration_seconds",
        "avg_hdop"
    ]
].sort_values(
    "n_signal_loss",
    ascending=False
)

display(high_signal_loss_tracks.to_string(index=False))

' vehicle_id  track_id  distance  avg_speed  max_speed  n_signal_loss  d_signal_loss  r_signal_loss  duration_seconds  avg_hdop\n         35     74784   20423.0       0.33      21.28       532659.0          246.0       0.012045         61784.027  0.950729\n         35     74708   42811.0       0.97      19.89       391263.0            3.0       0.000070         44175.197  0.693506\n         28     63263  213189.0       9.79      21.33       211555.0            0.0       0.000000         21785.660  0.816891\n         24     52439  249634.0      11.84      23.49       205715.0            0.0       0.000000         21083.700  0.947259\n         25     54541  185510.0       8.85      25.09       203732.0            0.0       0.000000         20959.446  0.676957\n         80    130715     578.0       0.03      25.89       200072.0            0.0       0.000000         21128.615  0.658859\n         24     53439  241239.0      11.73      20.70       197234.0            0.0       0.000000         20568.450  0.920359\n        121    139732  233692.0      11.39      26.16       195357.0            0.0       0.000000         20521.864  1.463905\n         24     52186     127.0       0.01      22.37       193783.0            0.0       0.000000         20655.402  0.786762\n         41     82436  286428.0      14.92      26.61       187516.0            0.0       0.000000         19193.477  0.567263\n        140    145099    1721.0       0.09      25.70       186244.0            0.0       0.000000         19634.191  1.054655\n         30     64585     657.0       0.03      24.84       185985.0            0.0       0.000000         20366.358  0.488442\n         93    133143     360.0       0.02      25.51       185740.0            0.0       0.000000         19054.295  0.803828\n         24     52940  238355.0      12.03      19.15       184678.0            0.0       0.000000         19817.158  0.856937\n         36     75952     381.0       0.02      25.93       182367.0            0.0       0.000000         19393.279  0.602419\n         28     63174     264.0       0.01      26.10       181924.0            0.0       0.000000         19142.189  1.350859\n         93    133132     516.0       0.03      26.99       181097.0            0.0       0.000000         18571.643  0.614339\n         30     64633   52921.0       2.52      19.46       180594.0          635.0       0.011999         21011.521  0.516529\n         24     53435  204302.0      11.04      22.38       179153.0            0.0       0.000000         18507.632  0.921705\n         80    130675  264472.0      13.81      25.98       177486.0            1.0       0.000004         19152.188  0.653554\n         93    133077  326508.0      17.21      26.52       176295.0           84.0       0.000257         18972.462  0.631675\n         91    132566    7558.0       0.41      26.45       173780.0            0.0       0.000000         18366.182  1.022405\n         43     83625  353663.0      19.46      26.24       171151.0            0.0       0.000000         18178.071  0.445589\n         39     79490  300237.0      16.28      25.68       170047.0            0.0       0.000000         18443.450  0.633426\n         54    104662  193152.0       9.93      26.17       168961.0            0.0       0.000000         19454.174  1.783535\n         29     64003   22969.0       1.32      23.73       168510.0            0.0       0.000000         17335.293  0.640189\n          6     10373     190.0       0.01      26.55       167918.0            0.0       0.000000         17223.580  0.892018\n         41     82163  303247.0      17.62      31.43       167600.0            3.0       0.000010         17210.866  0.760433\n         93    133159    1626.0       0.09      26.23       166988.0            0.0       0.000000         17589.143  0.978545\n        121    139730  243718.0      11.64      27.79       166540.0           39.0       0.000160         20936.097  1.452173\n         12     24029     219.0       0.01      29.71       166154.0            0.0       0.000000         17974.969  0.665404\n        121    139535     258.0       0.02      25.23       164405.0            0.0       0.000000         17034.382  1.615506\n         24     52840  182796.0      10.01      19.33       164362.0            0.0       0.000000         18266.794  0.983646\n          1       429  316450.0      18.31      27.78       164211.0            0.0       0.000000         17280.862  0.810680\n         26     58826     413.0       0.02      26.25       162880.0            0.0       0.000000         17118.195  0.785754\n         30     64589   58826.0       3.56      25.11       161621.0            0.0       0.000000         16526.492  0.492915\n         28     62638  204558.0      12.26      25.91       160769.0            0.0       0.000000         16686.557  1.273974\n        102    135303     573.0       0.03      27.31       160439.0            0.0       0.000000         16405.809  0.479891\n        148    146815  160947.0       9.90      25.18       160147.0            0.0       0.000000         16256.802  0.881262\n         12     25120  343905.0      19.63      28.67       159017.0            0.0       0.000000         17521.300  0.702257\n          1       772  358993.0      22.04      27.75       156710.0            0.0       0.000000         16288.086  0.726389\n         76    129321  302221.0      18.21      25.81       156652.0            0.0       0.000000         16594.910  0.519455\n          1       534  336699.0      20.99      27.77       156190.0            0.0       0.000000         16037.769  1.049845\n         62    121154  312943.0      19.03      25.53       155904.0            0.0       0.000000         16447.233  0.589221\n         24     52489  232813.0      14.28      20.73       155405.0            0.0       0.000000         16302.193  0.994739\n         44     87346  376872.0      23.64      31.70       154073.0            0.0       0.000000         15944.499  0.451443\n         36     76154     130.0       0.01      25.28       153688.0            0.0       0.000000         15997.495  0.634239\n         50     95481  320373.0      20.46      26.20       152884.0            0.0       0.000000         15659.863  0.552789\n         41     81684  293026.0      18.00      25.60       152705.0            0.0       0.000000         16278.100  0.528705\n         13     25905  330130.0      21.08      25.34       152293.0            0.0       0.000000         15663.884  1.958157\n          6     12120  318486.0      18.97      26.57       152216.0            1.0       0.000003         16787.347  0.924391\n         29     63882   46948.0       3.02      20.78       152128.0            0.0       0.000000         15545.618  0.521624\n         93    133063   89909.0       4.59      25.89       151959.0           52.0       0.000578         19594.357  0.673731\n         39     79909     143.0       0.01      26.58       151833.0            0.0       0.000000         16524.839  0.586476\n         62    121184    1303.0       0.08      24.70       151645.0           39.0       0.029931         16069.682  0.582851\n         91    132692  146088.0       9.40      25.27       150666.0            0.0       0.000000         15544.111  1.009674\n         47     90948   39731.0       2.23      25.03       149389.0          124.0       0.003121         17798.261  0.606826\n         62    121172     362.0       0.02      24.94       149272.0            0.0       0.000000         15781.532  0.594586\n          1       211  334703.0      22.06      28.01       148495.0            0.0       0.000000         15174.232  0.654266\n         80    130703  207435.0      12.29      26.54       147921.0            0.0       0.000000         16872.050  0.603904\n         49     94875  300032.0      19.73      26.29       147876.0            0.0       0.000000         15208.247  0.840953\n         47     91418  316475.0      20.16      25.12       147596.0            1.0       0.000003         15695.768  0.634091\n         13     27295  341460.0      21.58      27.21       147343.0            1.0       0.000003         15825.110  1.923229\n         49     94319  325867.0      21.93      26.23       144998.0            0.0       0.000000         14857.277  0.696930\n         74    128827  293201.0      19.39      25.59       144869.0            0.0       0.000000         15124.433  0.439475\n         45     87572  338314.0      22.51      27.05       144813.0            0.0       0.000000         15030.707  0.753409\n         51     98784  338719.0      22.72      27.13       144698.0            0.0       0.000000         14907.454  0.640715\n         41     82562  297622.0      20.00      26.02       144356.0            0.0       0.000000         14878.310  0.721259\n        102    135221    2938.0       0.19      26.71       144102.0            0.0       0.000000         15187.097  0.461793\n         45     88034  314944.0      20.74      26.59       144097.0            0.0       0.000000         15186.813  0.743014\n         51     98383    1370.0       0.09      28.43       143997.0            0.0       0.000000         15488.531  0.713116\n         62    121175  318529.0      20.51      24.39       143875.0            0.0       0.000000         15528.883  0.595392\n         59    114984  194742.0      12.74      25.85       143644.0            0.0       0.000000         15286.537  0.621570\n         59    117316  172491.0      10.69      30.58       143516.0            0.0       0.000000         16128.401  0.646224\n        150    147312    5761.0       0.34      26.76       143139.0            0.0       0.000000         16878.495  0.790285\n         41     83092  307906.0      20.55      26.10       142932.0            1.0       0.000003         14984.290  0.823752\n        110    137165     792.0       0.05      25.58       142849.0            0.0       0.000000         14965.339  1.218365\n         46     89162      91.0       0.01      26.69       142470.0            0.0       0.000000         14855.394  0.594190\n         45     88216  315002.0      21.34      28.76       142281.0            0.0       0.000000         14763.983  0.487272\n         52    100134     301.0       0.02      25.95       142226.0            0.0       0.000000         15536.358  0.591136\n         91    132568    2461.0       0.16      25.54       141859.0            0.0       0.000000         14956.474  0.996458\n         41     82412  312206.0      21.49      25.78       141264.0            0.0       0.000000         14528.086  0.786661\n         62    121157     156.0       0.01      24.73       141188.0            0.0       0.000000         14934.847  0.553186\n         53    101716  254356.0      17.11      26.70       140731.0            0.0       0.000000         14867.482  0.584140\n         56    110970  267878.0      18.08      25.96       140699.0            0.0       0.000000         14815.449  0.590590\n         13     27378      86.0       0.01      25.00       140533.0            0.0       0.000000         14923.129  1.956060\n         27     61868  169569.0      11.76      20.71       140113.0            0.0       0.000000         14418.711  1.018313\n         24     52313   38659.0       2.30      23.95       140083.0          172.0       0.004449         16837.168  0.687613\n         91    132493  184677.0       8.28      25.96       139729.0           57.0       0.000309         22293.408  0.723670\n         53    100764  247869.0      17.21      26.35       139527.0            0.0       0.000000         14401.196  0.551385\n         18     39697  249385.0      17.29      26.42       139485.0            0.0       0.000000         14424.759  1.384796\n         44     85976      82.0       0.01      27.15       139471.0            0.0       0.000000         14865.809  0.432623\n         36     76664     223.0       0.02      26.21       139303.0            0.0       0.000000         14599.443  0.636104\n        105    135968  207911.0      14.80      26.76       138983.0            0.0       0.000000         14047.655  0.993885\n         49     94465  357281.0      23.05      26.63       138770.0            0.0       0.000000         15501.006  0.583032\n         63    123314  311107.0      21.52      43.40       138728.0            0.0       0.000000         14456.766  0.969228\n         49     94352  269538.0      19.00      25.74       137961.0            0.0       0.000000         14182.964  0.679020\n        105    136145  201819.0      13.83      26.65       137543.0            0.0       0.000000         14597.225  0.895018\n         44     85688  319971.0      22.72      28.22       137395.0            2.0       0.000006         14083.163  0.459181\n         12     23537  378926.0      21.92      28.52       137333.0          102.0       0.000269         17287.589  0.613530\n         13     26009     213.0       0.01      26.68       137155.0            0.0       0.000000         14446.636  1.676204\n         52    100089  320843.0      22.74      26.53       136933.0            0.0       0.000000         14112.142  0.622081\n         47     90846    8993.0       0.59      27.09       136821.0           41.0       0.004559         15328.220  0.405939\n         39     79128    1043.0       0.07      26.31       136811.0            0.0       0.000000         15200.044  0.500810\n         24     52483  184652.0      12.28      20.62       136397.0            0.0       0.000000         15039.333  0.995925\n         38     78690  331040.0      21.67      25.94       136364.0            1.0       0.000003         15273.214  0.592444\n         45     87750     172.0       0.01      26.78       135713.0            0.0       0.000000         14071.001  0.632919\n         38     78419  249304.0      17.20      24.72       135474.0            0.0       0.000000         14497.765  0.632819\n        128    141316  294650.0      21.43      26.85       135431.0            0.0       0.000000         13746.750  1.408224\n        121    139528    2437.0       0.16      26.58       135276.0            0.0       0.000000         15073.154  1.618164\n         80    130581     421.0       0.03      26.22       134927.0            0.0       0.000000         14554.430  0.670914\n         80    130597  158724.0       8.58      26.04       134542.0           51.0       0.000321         18498.069  0.658321\n         53    101616  251116.0      17.70      26.86       134393.0            0.0       0.000000         14185.006  0.626815\n         46     88532     165.0       0.01      26.32       134094.0            1.0       0.006061         13684.244  0.617333\n         81    130875   21631.0       1.42      28.77       134034.0            0.0       0.000000         15183.899  0.774178\n         62    121166    8183.0       0.54      24.41       133879.0           61.0       0.007454         15251.035  0.569063\n         19     40623    2019.0       0.11      12.56       133763.0          145.0       0.071818         18938.331  0.903304\n         43     84019  294955.0      21.38      26.09       133121.0            0.0       0.000000         13797.833  0.536013\n         12     22997  287353.0      19.69      28.73       132053.0            0.0       0.000000         14592.677  0.644370\n        159    150312     107.0       0.01      25.43       131438.0            0.0       0.000000         13959.433  0.981573\n         24     53537  184216.0      13.50      19.93       131218.0           34.0       0.000185         13646.141  1.013892\n        146    146351  268205.0      14.50      25.31       130607.0          159.0       0.000593         18490.942  1.679829\n         59    116958     126.0       0.01      25.72       130588.0            0.0       0.000000         14670.072  0.738904\n        135    143287     262.0       0.02      26.61       130508.0            0.0       0.000000         13859.128  1.851904\n         75    129109     315.0       0.02      25.49       130410.0            0.0       0.000000         13279.077  0.580237\n         53    100752  263360.0      19.21      26.02       130326.0            0.0       0.000000         13706.315  0.551542\n         27     60982  221497.0      15.90      25.97       129681.0            0.0       0.000000         13933.536  1.101138\n        129    141368     387.0       0.03      26.03       129519.0            0.0       0.000000         13542.683  1.462847\n         24     53115  147124.0      11.02      20.46       129503.0            0.0       0.000000         13352.349  0.750575\n         45     88189      98.0       0.01      26.11       129276.0            0.0       0.000000         13335.504  0.484017\n        126    140601  161859.0      12.24      26.34       129136.0            0.0       0.000000         13222.640  2.859095\n         50     97525  311968.0      23.25      27.59       129126.0            0.0       0.000000         13416.959  0.542664\n         41     81875    1872.0       0.13      25.13       129092.0            0.0       0.000000         14928.257  0.557723\n         51     98675    2052.0       0.14      26.26       128852.0            0.0       0.000000         14465.166  0.595773\n          4      6681  112879.0       8.51      24.51       128768.0            0.0       0.000000         13261.564  0.439795\n         59    115190    8825.0       0.63      25.71       128421.0           35.0       0.003966         14053.519  0.670801\n         16     30920  237821.0      18.00      26.38       128394.0            0.0       0.000000         13214.041  1.120576\n         12     22911  293374.0      21.85      25.54       128021.0            0.0       0.000000         13428.643  0.628640\n         56    110634  282804.0      21.10      25.46       128006.0            0.0       0.000000         13401.177  0.803152\n         26     60220  232140.0      16.11      26.74       127792.0            0.0       0.000000         14413.848  1.455258\n         51     97921  279425.0      20.88      26.50       127784.0            0.0       0.000000         13383.263  0.594773\n         50     96244     702.0       0.05      25.94       127584.0            0.0       0.000000         14120.669  0.545022\n        146    146350    3337.0       0.25      25.66       127519.0            0.0       0.000000         13201.164  1.705798\n        137    144078     999.0       0.07      28.63       127300.0            0.0       0.000000         14264.162  1.157002\n         41     83131  187499.0      14.10      24.59       127282.0            0.0       0.000000         13299.257  0.731854\n         28     62888     351.0       0.03      25.86       127183.0            0.0       0.000000         13929.810  1.029118\n         50     95754  255740.0      19.71      25.64       126993.0            0.0       0.000000         12978.394  0.877026\n         48     93661      95.0       0.01      26.36       126805.0            0.0       0.000000         13849.874  0.662769\n        134    143251     235.0       0.02      25.04       126765.0            0.0       0.000000         13108.091  0.892947\n         21     47367  219853.0      16.05      28.53       126676.0            1.0       0.000005         13700.115  1.007248\n          1       757  269965.0      19.92      26.52       126330.0           66.0       0.000244         13553.383  0.636625\n         50     96265      80.0       0.01      25.51       125376.0            0.0       0.000000         12952.341  0.660703\n         38     78957  264514.0      20.21      25.07       125122.0            0.0       0.000000         13090.000  0.707245\n         47     91706  275562.0      20.72      25.98       124829.0            0.0       0.000000         13296.707  0.456257\n         59    116919     137.0       0.01      26.59       124184.0            0.0       0.000000         13897.780  0.752801\n          6     10923   52478.0

In [52]:
# Screen for extreme signal-loss counts
high_signal_loss = features.loc[
    features["n_signal_loss"] >= 100_000
].copy()

# High counts with recorded movement
high_signal_loss_moving = high_signal_loss.loc[
    (high_signal_loss["distance"] > 0)
    & (high_signal_loss["avg_speed"] > 0)
].copy()

print("Total tracks:", len(features))
print("Tracks with n_signal_loss >= 100,000:", len(high_signal_loss))
print(
    "High-count tracks with positive distance and speed:",
    len(high_signal_loss_moving)
)
print(
    "High-count tracks with zero distance or non-positive speed:",
    len(high_signal_loss) - len(high_signal_loss_moving)
)

print("\nSignal-loss count distribution among moving tracks:")
print(
    high_signal_loss_moving["n_signal_loss"]
    .describe(percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99])
)

Total tracks: 151598
Tracks with n_signal_loss >= 100,000: 404
High-count tracks with positive distance and speed: 305
High-count tracks with zero distance or non-positive speed: 99

Signal-loss count distribution among moving tracks:
count       305.000000
mean     131939.462295
std       36274.492359
min      100396.000000
25%      111784.000000
50%      125122.000000
75%      142849.000000
90%      165454.400000
95%      181758.600000
99%      205635.680000
max      532659.000000
Name: n_signal_loss, dtype: float64

In [53]:
high_signal_loss_operational = features.loc[
    (features["n_signal_loss"] >= 100_000)
    & (features["distance"] > 1000)
    & (features["avg_speed"] > 0)
].copy()

print(
    "High-count moving tracks in operational dataset:",
    len(high_signal_loss_operational)
)

print(
    "Percentage of operational dataset:",
    round(
        len(high_signal_loss_operational)
        / (features["distance"] > 1000).sum()
        * 100,
        3
    ),
    "%"
)

High-count moving tracks in operational dataset: 210
Percentage of operational dataset: 0.487 %

In [54]:
skewness_columns = [
    "r_signal_loss_valid",
    "distance_km",
    "avg_speed_kmh",
    "max_speed_kmh",
    "raw_speed_mean_kmh",
    "duration_minutes"
]

skewness_summary = (
    features[skewness_columns]
    .skew()
    .sort_values(ascending=False)
    .rename("skewness")
    .to_frame()
)

display(skewness_summary)

                      skewness
avg_speed_kmh        52.939378
r_signal_loss_valid  10.527364
distance_km           4.284422
duration_minutes      3.434279
raw_speed_mean_kmh    1.834900
max_speed_kmh         1.107065

In [55]:
operational = features.loc[
    features["distance_km"] > 1
].copy()

speed_columns = [
    "vehicle_id",
    "track_id",
    "distance_km",
    "duration_minutes",
    "avg_speed_kmh",
    "max_speed_kmh",
    "raw_speed_mean_kmh",
    "speed_distance_validity"
]

print("Operational tracks:", len(operational))

display(
    operational[speed_columns]
    .sort_values("avg_speed_kmh", ascending=False)
    .head(20)
)

Operational tracks: 43125

,vehicle_id,track_id,distance_km,duration_minutes,avg_speed_kmh,max_speed_kmh,raw_speed_mean_kmh,speed_distance_validity
138274,114,138274,277.421,3.756667,4430.844,8.388,1.931023,invalid
49132,22,49132,182.083,2.706517,4036.536,32.940,7.055322,invalid
135017,102,135017,68.080,1.085617,3762.648,24.696,7.042904,invalid
102170,54,102170,17.535,0.280250,3754.152,0.252,0.083494,invalid
93407,48,93407,104.576,2.277983,2754.432,0.324,0.080933,invalid
9707,5,9707,12.865,0.280383,2753.028,0.252,0.093036,invalid
138899,118,138899,117.550,2.644717,2666.844,24.408,3.576502,invalid
91783,47,91783,226.810,5.702400,2386.476,35.640,11.022743,invalid
143352,135,143352,106.570,2.738200,2335.176,48.816,20.892816,invalid
150232,159,150232,88.133,2.312567,2286.612,16.380,3.786467,invalid
104890,54,104890,39.176,1.279283,1837.404,17.748,5.691676,invalid
114748,59,114748,149.795,5.131883,1751.364,3.420,0.082304,invalid
103102,54,103102,99.819,3.562450,1681.200,8.136,0.410397,invalid
29944,15,29944,269.965,10.478233,1545.876,67.392,35.659398,invalid
105234,54,105234,114.082,4.703800,1455.192,19.332,4.859701,invalid
61101,27,61101,92.787,3.847283,1447.056,4.140,0.962849,invalid
132992,92,132992,69.171,3.706750,1119.636,10.368,0.589323,invalid
131935,88,131935,75.433,4.221217,1072.188,41.580,11.074756,invalid
146128,146,146128,62.017,3.812167,976.104,0.864,0.172740,invalid
11767,6,11767,170.415,10.603417,964.296,0.468,0.087016,invalid

In [56]:
review_columns = [
    "r_signal_loss_valid",
    "duration_minutes",
    "raw_speed_mean_kmh",
    "max_speed_kmh"
]

operational = features.loc[
    features["distance_km"] > 1
].copy()

for col in review_columns:
    s = operational[col]

    print(f"\n{'=' * 55}")
    print(f"Column: {col}")
    print(f"Missing: {s.isna().sum():,}")
    print(f"Zero: {(s == 0).sum():,}")
    print(f"Negative: {(s < 0).sum():,}")
    print(f"Positive: {(s > 0).sum():,}")
    print("\nQuantiles:")
    print(
        s.quantile([
            0.00, 0.25, 0.50, 0.75,
            0.90, 0.95, 0.99, 1.00
        ])
    )

=======================================================
Column: r_signal_loss_valid
Missing: 20
Zero: 12,993
Negative: 0
Positive: 30,112

Quantiles:
0.00    0.000000
0.25    0.000000
0.50    0.001887
0.75    0.009080
0.90    0.032883
0.95    0.073351
0.99    0.201998
1.00    0.999830
Name: r_signal_loss_valid, dtype: float64

=======================================================
Column: duration_minutes
Missing: 4
Zero: 0
Negative: 0
Positive: 43,121

Quantiles:
0.00       0.280250
0.25      20.414850
0.50      42.380767
0.75      83.035700
0.90     141.672117
0.95     193.254467
0.99     264.632013
1.00    1029.733783
Name: duration_minutes, dtype: float64

=======================================================
Column: raw_speed_mean_kmh
Missing: 4
Zero: 0
Negative: 0
Positive: 43,121

Quantiles:
0.00      0.063221
0.25     17.869728
0.50     38.783499
0.75     57.245378
0.90     69.211960
0.95     74.084156
0.99     80.234676
1.00    255.226737
Name: raw_speed_mean_kmh, dtype: float64

=======================================================
Column: max_speed_kmh
Missing: 0
Zero: 0
Negative: 0
Positive: 43,125

Quantiles:
0.00      0.252
0.25     67.788
0.50     82.548
0.75     91.080
0.90     94.032
0.95     95.976
0.99    102.492
1.00    455.940
Name: max_speed_kmh, dtype: float64

In [57]:
import numpy as np
import pandas as pd

operational = features.loc[
    features["distance_km"] > 1
].copy()

candidate_columns = [
    "avg_speed_kmh",
    "r_signal_loss_valid"
]

for col in candidate_columns:
    q1 = operational[col].quantile(0.25)
    q3 = operational[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    operational[f"{col}_outlier_flag"] = (
        (operational[col] < lower_bound)
        | (operational[col] > upper_bound)
    )

    print(f"\n{col}")
    print(f"Lower bound: {lower_bound:.4f}")
    print(f"Upper bound: {upper_bound:.4f}")
    print(
        "Flagged:",
        operational[f"{col}_outlier_flag"].sum()
    )

avg_speed_kmh
Lower bound: -41.5980
Upper bound: 116.0820
Flagged: 240

r_signal_loss_valid
Lower bound: -0.0136
Upper bound: 0.0227
Flagged: 5191

In [58]:
review_columns = [
    "vehicle_id",
    "track_id",
    "distance_km",
    "duration_minutes",
    "avg_speed_kmh",
    "max_speed_kmh",
    "raw_speed_mean_kmh",
    "r_signal_loss_valid"
]

print("Highest average-speed outliers:")
display(
    operational.loc[
        operational["avg_speed_kmh_outlier_flag"],
        review_columns
    ]
    .sort_values("avg_speed_kmh", ascending=False)
    .head(20)
)

print("\nHighest signal-loss-ratio outliers:")
display(
    operational.loc[
        operational["r_signal_loss_valid_outlier_flag"],
        review_columns
    ]
    .sort_values("r_signal_loss_valid", ascending=False)
    .head(20)
)

Highest average-speed outliers:

,vehicle_id,track_id,distance_km,duration_minutes,avg_speed_kmh,max_speed_kmh,raw_speed_mean_kmh,r_signal_loss_valid
138274,114,138274,277.421,3.756667,4430.844,8.388,1.931023,0.000000
49132,22,49132,182.083,2.706517,4036.536,32.940,7.055322,0.005399
135017,102,135017,68.080,1.085617,3762.648,24.696,7.042904,0.001381
102170,54,102170,17.535,0.280250,3754.152,0.252,0.083494,0.002851
93407,48,93407,104.576,2.277983,2754.432,0.324,0.080933,0.000392
9707,5,9707,12.865,0.280383,2753.028,0.252,0.093036,0.000000
138899,118,138899,117.550,2.644717,2666.844,24.408,3.576502,0.000000
91783,47,91783,226.810,5.702400,2386.476,35.640,11.022743,0.006724
143352,135,143352,106.570,2.738200,2335.176,48.816,20.892816,0.000019
150232,159,150232,88.133,2.312567,2286.612,16.380,3.786467,0.000000
104890,54,104890,39.176,1.279283,1837.404,17.748,5.691676,0.000051
114748,59,114748,149.795,5.131883,1751.364,3.420,0.082304,0.000000
103102,54,103102,99.819,3.562450,1681.200,8.136,0.410397,0.000000
29944,15,29944,269.965,10.478233,1545.876,67.392,35.659398,0.000244
105234,54,105234,114.082,4.703800,1455.192,19.332,4.859701,0.000000
61101,27,61101,92.787,3.847283,1447.056,4.140,0.962849,0.000000
132992,92,132992,69.171,3.706750,1119.636,10.368,0.589323,0.003687
131935,88,131935,75.433,4.221217,1072.188,41.580,11.074756,0.000000
146128,146,146128,62.017,3.812167,976.104,0.864,0.172740,0.000000
11767,6,11767,170.415,10.603417,964.296,0.468,0.087016,0.004202

Highest signal-loss-ratio outliers:

,vehicle_id,track_id,distance_km,duration_minutes,avg_speed_kmh,max_speed_kmh,raw_speed_mean_kmh,r_signal_loss_valid
2775,2,2775,5.865,2.519133,139.680,305.352,255.226737,0.999830
2807,2,2807,2.449,2.384017,61.632,59.868,2.862720,0.997958
3845,2,3845,4.299,3.994050,64.584,15.696,2.275463,0.996743
64481,30,64481,67.756,155.315250,26.172,69.696,12.249830,0.994923
140440,126,140440,7.234,57.708817,7.524,86.976,16.070010,0.994471
3318,2,3318,2.198,4.470733,29.484,208.188,2.193449,0.994086
3896,2,3896,11.005,2.984500,221.256,209.052,12.960000,0.993548
2644,2,2644,19.292,17.911017,64.620,316.260,55.140904,0.991240
2792,2,2792,5.416,3.907117,83.160,455.940,5.936354,0.988368
2616,2,2616,9.280,12.187333,45.684,212.544,141.458667,0.987500
3529,2,3529,6.705,4.403500,91.368,110.592,21.636000,0.987174
26144,13,26144,2.563,2.226283,69.084,29.520,11.037778,0.982833
3154,2,3154,2.078,14.506683,8.604,227.484,192.717818,0.973051
145823,144,145823,26.941,82.899667,19.512,93.384,61.529858,0.960803
2828,2,2828,5.322,5.314000,60.084,184.284,102.480608,0.952837
6855,4,6855,3.707,198.401033,1.116,96.048,68.964197,0.951713
3526,2,3526,7.282,8.041667,54.324,211.536,10.532053,0.950151
2611,2,2611,5.865,2.091033,168.300,163.044,94.252444,0.944928
2824,2,2824,18.307,189.723450,5.796,65.808,4.806166,0.938493
4074,2,4074,11.555,111.270633,6.228,69.156,9.134443,0.936478

In [59]:
# Work with the existing operational dataset and IQR flags.

signal_speed_review = operational[
    [
        "track_id",
        "avg_speed_kmh",
        "max_speed_kmh",
        "raw_speed_mean_kmh",
        "r_signal_loss_valid",
        "avg_speed_kmh_outlier_flag",
        "r_signal_loss_valid_outlier_flag"
    ]
].copy()

high_signal_ratio = signal_speed_review[
    signal_speed_review["r_signal_loss_valid_outlier_flag"]
]

print("High signal-loss-ratio tracks:", len(high_signal_ratio))

print(
    "Also flagged for average speed:",
    high_signal_ratio["avg_speed_kmh_outlier_flag"].sum()
)

print(
    "Percentage also flagged for average speed:",
    round(
        high_signal_ratio["avg_speed_kmh_outlier_flag"].mean() * 100,
        2
    ),
    "%"
)

High signal-loss-ratio tracks: 5191
Also flagged for average speed: 35
Percentage also flagged for average speed: 0.67 %

In [60]:
high_signal_ratio = operational.loc[
    operational["r_signal_loss_valid_outlier_flag"]
].copy()

inconsistent_speed = (
    high_signal_ratio["avg_speed_kmh"]
    > high_signal_ratio["max_speed_kmh"]
)

print("High signal-loss-ratio tracks:", len(high_signal_ratio))
print(
    "Tracks where avg_speed_kmh > max_speed_kmh:",
    inconsistent_speed.sum()
)
print(
    "Percentage:",
    round(inconsistent_speed.mean() * 100, 2),
    "%"
)

High signal-loss-ratio tracks: 5191
Tracks where avg_speed_kmh > max_speed_kmh: 61
Percentage: 1.18 %

In [61]:
# Check whether speed columns are duplicate unit conversions.

checks = {
    "avg_speed_valid vs avg_speed_kmh":
        ("avg_speed_valid", "avg_speed_kmh", 3.6),
    "max_speed_valid vs max_speed_kmh":
        ("max_speed_valid", "max_speed_kmh", 3.6),
}

for label, (col1, col2, factor) in checks.items():
    comparison = features[[col1, col2]].dropna()
    difference = (
        comparison[col1] * factor - comparison[col2]
    ).abs()

    print(f"\n{label}")
    print("Rows compared:", len(comparison))
    print("Maximum absolute difference:", difference.max())
    print("Exact matches:", (difference < 1e-6).sum())

avg_speed_valid vs avg_speed_kmh
Rows compared: 151543
Maximum absolute difference: 0.0
Exact matches: 151543

max_speed_valid vs max_speed_kmh
Rows compared: 151549
Maximum absolute difference: 0.0
Exact matches: 151549

In [62]:
col = "d_signal_loss"

print("Summary statistics:")
print(features[col].describe(percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]))

print("\nMissing values:", features[col].isna().sum())
print("Negative values:", (features[col] < 0).sum())
print("Zero values:", (features[col] == 0).sum())
print("Positive values:", (features[col] > 0).sum())

print("\nSkewness:", features[col].skew())

Summary statistics:
count    151549.000000
mean        198.464549
std        1391.952990
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
90%         143.000000
95%         706.000000
99%        4188.000000
max       67936.000000
Name: d_signal_loss, dtype: float64

Missing values: 49
Negative values: 0
Zero values: 111918
Positive values: 39631

Skewness: 18.324965887213494

In [63]:
cols = [
    "d_signal_loss",
    "distance_km",
    "r_signal_loss_valid"
]

print(features[cols].corr())

                     d_signal_loss  distance_km  r_signal_loss_valid
d_signal_loss             1.000000     0.393862             0.298758
distance_km               0.393862     1.000000             0.027204
r_signal_loss_valid       0.298758     0.027204             1.000000

In [64]:
operational = features.loc[features["distance_km"] > 1].copy()

print(
    operational[
        ["d_signal_loss", "distance_km", "r_signal_loss_valid"]
    ].corr()
)

                     d_signal_loss  distance_km  r_signal_loss_valid
d_signal_loss             1.000000     0.334099             0.486646
distance_km               0.334099     1.000000            -0.025424
r_signal_loss_valid       0.486646    -0.025424             1.000000

In [65]:
col = "d_signal_loss"

print("Missing:", operational[col].isna().sum())
print("Negative:", (operational[col] < 0).sum())
print("Zero:", (operational[col] == 0).sum())
print("Positive:", (operational[col] > 0).sum())

print("\nDistribution:")
print(
    operational[col].describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nSkewness:", operational[col].skew())

Missing: 0
Negative: 0
Zero: 12993
Positive: 30132

Distribution:
count    43125.000000
mean       690.369577
std       2537.689465
min          0.000000
25%          0.000000
50%         35.000000
75%        326.000000
90%       1588.000000
95%       3111.800000
99%      11614.000000
max      67936.000000
Name: d_signal_loss, dtype: float64

Skewness: 10.01744145712759

In [66]:
q1 = operational["d_signal_loss"].quantile(0.25)
q3 = operational["d_signal_loss"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

operational["d_signal_loss_iqr_outlier"] = (
    (operational["d_signal_loss"] < lower_bound) |
    (operational["d_signal_loss"] > upper_bound)
)

print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Candidate outliers:",
      operational["d_signal_loss_iqr_outlier"].sum())

Q1: 0.0
Q3: 326.0
IQR: 326.0
Lower bound: -489.0
Upper bound: 815.0
Candidate outliers: 6888

In [67]:
cols = [
    "vehicle_id",
    "track_id",
    "distance_km",
    "duration_minutes",
    "avg_speed_kmh",
    "max_speed_kmh",
    "raw_speed_mean_kmh",
    "d_signal_loss",
    "r_signal_loss_valid",
]

extreme_tracks = (
    operational.nlargest(20, "d_signal_loss")[cols]
)

print(extreme_tracks.to_string(index=False))

 vehicle_id  track_id  distance_km  duration_minutes  avg_speed_kmh  max_speed_kmh  raw_speed_mean_kmh  d_signal_loss  r_signal_loss_valid
        113    137895      132.151        126.120667         62.856        116.172           64.144388        67936.0             0.514079
         76    129448      170.665        231.244650         44.280         89.316           55.850488        67885.0             0.397768
         30     64481       67.756        155.315250         26.172         69.696           12.249830        67412.0             0.994923
         20     42601      157.038        177.740767         53.028        105.552           64.715685        63720.0             0.405762
        147    146550       70.803        112.923683         37.620         96.408           46.471488        60358.0             0.852478
        135    143468       71.177         87.398650         48.852         88.308           62.089892        59268.0             0.832685
        126    140434       68.556         93.744950         43.884         97.992           74.780871        55362.0             0.807544
        140    145101      140.583        153.973550         54.792         90.936           57.092335        53939.0             0.383681
         20     42595      179.254        164.451283         65.412         97.848           70.327906        50451.0             0.281450
        147    146431      120.276        119.712450         60.300         97.380           63.582863        49769.0             0.413790
          2      2657       61.857        337.912050         10.980        124.308           33.907459        47615.0             0.769759
        113    137919      134.917        123.771083         65.412        114.912           66.037453        45701.0             0.338734
        136    143804      133.191        145.272700         55.008         90.288           63.291137        44106.0             0.331149
         54    104752      268.334         55.513417        290.016         85.608           52.354006        43023.0             0.160334
         55    108903      268.334        210.043183         76.644         95.508           76.159208        43023.0             0.160334
         55    109022      268.377        219.682783         73.296        102.600           72.936109        42588.0             0.158687
          2      3148       89.236        337.018417         15.876        302.976           23.741905        42499.0             0.476254
         55    107724      276.274         70.642167        234.648         90.684           70.831722        41958.0             0.151871
         55    108891      276.274        290.128733         57.132         97.164           73.957552        41958.0             0.151871
         55    108871      268.471        204.358067         78.840         94.428           79.006610        41432.0             0.154326

In [68]:
operational["distance_m"] = operational["distance_km"] * 1000

operational["signal_distance_exceeds_track"] = (
    operational["d_signal_loss"] > operational["distance_m"]
)

print(
    "Tracks where signal-loss distance exceeds total track distance:",
    operational["signal_distance_exceeds_track"].sum()
)

print(
    operational.loc[
        operational["signal_distance_exceeds_track"],
        [
            "vehicle_id",
            "track_id",
            "distance_km",
            "d_signal_loss",
            "r_signal_loss_valid",
        ],
    ].head(20).to_string(index=False)
)

Tracks where signal-loss distance exceeds total track distance: 20
 vehicle_id  track_id  distance_km  d_signal_loss  r_signal_loss_valid
         15     28972        2.115         3528.0                  NaN
         18     39102       13.172        36200.0                  NaN
         22     49759        1.612         1853.0                  NaN
         29     64197        1.902         1916.0                  NaN
         43     84264        2.960         3405.0                  NaN
         44     87274        1.220         3048.0                  NaN
         45     88074        1.075         1240.0                  NaN
         54    103288       29.916        31697.0                  NaN
         54    103882        5.150        20991.0                  NaN
         59    116380        1.422         5185.0                  NaN
         59    116381        1.422         5185.0                  NaN
         59    117023        5.769         9053.0                  NaN
         61    118257        3.969        23952.0                  NaN
         61    118258        3.969        23952.0                  NaN
         77    129579        1.027         1686.0                  NaN
         77    129598        1.948         6605.0                  NaN
         93    133221        1.128         2019.0                  NaN
        116    138565        5.798        13551.0                  NaN
        144    145818        1.539         6041.0                  NaN
        151    147683        2.746         5324.0                  NaN

In [69]:
operational["d_signal_loss_validity"] = np.where(
    operational["d_signal_loss"] <= operational["distance_km"] * 1000,
    "valid",
    "invalid"
)

print(operational["d_signal_loss_validity"].value_counts())

d_signal_loss_validity
valid      43105
invalid       20
Name: count, dtype: int64

In [70]:
# Vehicle concentration among signal-distance inconsistencies
invalid_signal_distance = operational[
    operational["d_signal_loss_validity"] == "invalid"
]

print("Invalid records by vehicle:")
print(
    invalid_signal_distance["vehicle_id"]
    .value_counts()
    .sort_values(ascending=False)
)

# Check repeated combinations of total distance and signal-loss distance
print("\nRepeated distance combinations:")
print(
    operational.groupby(
        ["distance_km", "d_signal_loss"]
    ).size()
    .loc[lambda s: s > 1]
    .sort_values(ascending=False)
    .head(20)
)

Invalid records by vehicle:
vehicle_id
59     3
54     2
61     2
77     2
15     1
18     1
22     1
29     1
43     1
44     1
45     1
93     1
116    1
144    1
151    1
Name: count, dtype: int64

Repeated distance combinations:
distance_km  d_signal_loss
1.075        0.0              15
1.014        0.0              15
1.030        0.0              14
1.025        0.0              14
1.045        0.0              13
1.055        0.0              13
1.056        0.0              13
1.009        0.0              12
1.062        0.0              12
1.023        0.0              12
1.011        0.0              12
1.001        0.0              12
1.042        0.0              12
1.022        0.0              11
1.028        0.0              11
1.059        0.0              10
1.016        0.0              10
1.038        0.0              10
1.019        0.0              10
1.178        0.0              10
dtype: int64

In [71]:
print(
    operational["d_signal_loss_validity"]
    .value_counts()
    .to_string()
)

print(
    "\nInvalid percentage:",
    (
        operational["d_signal_loss_validity"].eq("invalid").mean()
        * 100
    )
)

print(
    "\nSkewness among consistency-valid records:",
    operational.loc[
        operational["d_signal_loss_validity"] == "valid",
        "d_signal_loss"
    ].skew()
)

d_signal_loss_validity
valid      43105
invalid       20

Invalid percentage: 0.0463768115942029

Skewness among consistency-valid records: 10.084868300495327

In [72]:

from pathlib import Path

# Confirm that the engineered DataFrame exists
if "features" not in globals():
    raise NameError(
        "The DataFrame 'features' was not found. "
        "Run the feature-engineering cells first."
    )

# Set the output directory relative to the current working directory.
# If your notebook is in the notebooks/ folder, the project root is its parent.
cwd = Path.cwd()

if cwd.name == "notebooks":
    project_root = cwd.parent
else:
    project_root = cwd

output_dir = project_root / "data" / "processed"
output_dir.mkdir(parents=True, exist_ok=True)

# Output file for the PCA notebook
engineered_path = output_dir / "engineered_tracks.csv"

# Save the full engineered dataset without changing the DataFrame
features.to_csv(engineered_path, index=False)

# Verify the saved file
print("=" * 50)
print("ENGINEERED DATASET SAVED")
print("=" * 50)
print(f"Project root: {project_root}")
print(f"File path:    {engineered_path.resolve()}")
print(f"Rows:         {features.shape[0]:,}")
print(f"Columns:      {features.shape[1]}")
print(f"File exists:  {engineered_path.exists()}")
print(f"File size:    {engineered_path.stat().st_size / (1024**2):.2f} MB")
print("=" * 50)

==================================================
ENGINEERED DATASET SAVED
==================================================
Project root: /Users/janibhargesh/Documents/ML-Project
File path:    /Users/janibhargesh/Documents/ML-Project/data/processed/engineered_tracks.csv
Rows:         151,598
Columns:      63
File exists:  True
File size:    78.63 MB
==================================================